Char_creation/c_classes_bw.json
Removes bionic that @kevingranade gave the axe to. Fucked if I know why.
=> Removes solar CBM from Beta

Char_creation/c_classes_bw.json, Char_creation/c_scenarios.json, Npc/c_mission_def.json
-fixed mission bug appearing outside NPC mission givers.
-re-balanced bio-weapon professions
-re-balanced super soldier professions
=> Fix mission bug + misc changes

Weapons/c_ranged_override.json
Did the thing to lint ranged override.
=> Lint new file

Char_creation/c_scenarios.json
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/14
As mentioned in the issue, will want @BorkBorkGoesTheCode to tell us if they spot any PRs concerning More Classes and Scenarios, just in case the issue crops up again.
=> Remove bionic monster from experiment scneario

Char_creation/c_scenarios.json
-Fixed Prepper household having the survivor professions.
-Added New scenario from personal mod patch.
=> Updates to scenarios

Char_creation/c_scenarios.json
=> Added burglar profession to Last Jig Scenario

Mutations/c_bio_mutation_category.json
closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/26
* Added the now-required threshold mutation entry.
* Smol run of linting on the file.
Gave it a quick test on the latest available build, seems that just adding `threshold_mut` is sufficient.
=> Update Bio-weapon mutation category

Surv_help/c_tools.json
* Updates the use action.
* Also removes now-unused flag for strong mutagen.
=> Fix organic infusion set

Surv_help/c_bionics.json
* Implements use of copy-from for the bionic items.
* File lint.
Tested and all three seem to work as expected not only in vanilla, but in Bright Nights. Still, hopefully I didn't miss anything.
=> Updates to CBMs

Monsters/c_monsters.json
* Same outcome as before the change, lemme know if any of the bio-weapons and/or super soldiers should behave differently.
=> Applies new FILTHY tag to zombies and fungals

Char_creation/c_classes_bw.json, Monsters/c_speech.json
* Fixes Bio-Weapon Delta and super soldier scouts having two furnace CBMs.
* Added parrot entries for monsters that call the attack.
=> Furnace fix, parrot entries

Char_creation/c_classes_bw.json
Just some flavor changes to get them ready for some mutation changes I have in mind,
=> Super Soldier Professions Update (Part: 1)

Npc/TALK_BFF.json, Weapons/c_ranged.json
* Fixed the dialogue that now uses a different syntax.
* Added brass catcher slot.
=> Post-stable fixes

Npc/c_mission_def.json
Fixes Evelyn Rose's mission counting the wrong place as the destination.
=> Fix Evy's mission

Surv_help/c_snippets.json
This adds some ideas I had for some survivor's notes and newspaper snippets, related to the mod since quite a few assorted mods add relevant snippets.
=> Add snippet entries

Surv_help/c_martialarts.json
* Adds the new initiate property that's required.
* Couple minor typo fixes on the side.
=> Add missing parameter to Survivor Combatives

Surv_help/c_martialarts.json
=> Update buff descriptions

Recipe/c_recipes.json
Just makes survivor weapons use their proper full auto receivers in their crafting recipes.
=> Fixes survivor weapon recipes

Surv_help/c_tools.json
* Set it to be able to actually be able to hold the 5 charges required, and not use turns_per_charge.
=> Infusion tool fixes

Surv_help/c_tools.json
Simple enough, if anything it's sad that vanilla forges lack this, but for stationary ones that'd have some technical issues if I recall.
=> Add repair function to can forge

Surv_help/c_martialarts.json, Surv_help/c_techniques.json
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/179
=> Fixes changed martial art API

Npc/c_classes.json
This resolves the "duplicate entry" thing that comments now risk triggering.
=> Comment fix

README.md
Oops, those links look hideous.
=> Make the readme look nicer

Weapons/c_magazines.json
=> Correct coverage data to wearable ammo belts

README.md
I'll eventually make this readme as pretty as the one from the arcana repo, once I add all the missing content into it.
=> Add mod update info to the readme

Mutations/c_bio_mutation.json, Recipe/c_recipes.json
* Added varying activity levels to recipes.
* Added a small addition to Alpha's trait, since ability to overeat has been JSONnized.
=> Activity levels for recipes, addition to Alpha

nocts_cata_mod_BN/Recipe/c_recipes.json, nocts_cata_mod_DDA/Recipe/c_recipes.json
* Added a few additional books as options for making a makeshift autoclave.
* Added a recipe for making autoclave pouches, no mechanics involved and more focus on first aid as the most relevant subskill.
=> Updates to autoclave stuff

nocts_cata_mod_DDA/Surv_help/c_bionics.json
This fixes how there's now multiple types of pseudo-item for bionics in the DDA version, fixing load errors.
=> Update bionics for DDA version

nocts_cata_mod_BN/Surv_help/c_armor.json, nocts_cata_mod_DDA/Surv_help/c_armor.json
Another case of an active item vanishing when depleted, easy fix.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/331
=> Fix carapace arnor lacking revert entry

nocts_cata_mod_BN/Surv_help/c_bionics.json
Damnit, I thought I checked for obvious fuckups like that.
=> Quickfix for a typo

nocts_cata_mod_BN/Surv_help/c_martialartsbook.json, nocts_cata_mod_DDA/Surv_help/c_martialartsbook.json
Unfortunate but after some further testing it seems the "get skills from it" feature is still not ideal for martial arts books.
One tester found that if you get lucky and learn the style before you've learned all the skill you can out of it, it stops working as a skillbook.
Meanwhile I found that actually learning the style is several times harder with it also being given skillbook data, even after you've maxed out the skill it teaches. Wasn't able to confirm whether you even can learn the style after you max out the skill being taught, just that 24+ hours of uninterrupted training at max skills didn't yield progress.
And whoops, it always feels messier when I forget to create a branch and accidentally commit to my fork's master branch, even if net result is basically the same.
=> Convert the martial arts books to act like vanilla ones

nocts_cata_mod_DDA/Surv_help/c_armor.json
Fix of missing armor values by updating to comply with new DDA format.
=> Missing armor value fix

nocts_cata_mod_DDA/Mutations/c_bio_mutation.json
Some basic copy-paste mistakes on my end when implementing the DDA version of these changes, involving stuff I forgot was changed.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/352
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/353
=> Fixes for DDA version

nocts_cata_mod_DDA/Surv_help/c_armor.json
Easy fix, fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/363
=> Typofix for mil armor in DDA version

nocts_cata_mod_BN/Monsters/c_monster_harvest.json, nocts_cata_mod_DDA/Monsters/c_monster_harvest.json
That was a copypaste mistake on my part, it seems. Whoops!
=> Fix mi-gos yielding normal meat and fat

nocts_cata_mod_DDA/Surv_help/c_materials.json
Just adds a breathability value to the composite material used by military armor.
=> Breathability update for DDA version

nocts_cata_mod_BN/Surv_help/c_spells.json, nocts_cata_mod_DDA/Surv_help/c_spells.json
Lil oops, used duration instead of damage.
=> Quickfix for resin spinneret spell

nocts_cata_mod_BN/Surv_help/c_item_groups_modcompat.json
For consistency with DDA version of the Arcana/Cata++ patchmod.
=> Modcompat update

nocts_cata_mod_DDA/legacy.json
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/413
=> Remove old migration from DDA version

nocts_cata_mod_BN/Weapons/c_mods.json
Easy enough lil fix for BN version
=> Update bow gunmod

nocts_cata_mod_BN/Char_creation/c_classes_bw.json, nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
Turns out having this can give you Carnivore which then makes you unable to eat Mycus fruits.
Potentially I could tinker with improvements to BN's Mycus content in the future too to improve this but is a fast way to correct it plus DDA likely will still run into this.
=> Remove Unstable Genetics from fungal bio-weapon

nocts_cata_mod_DDA/Surv_help/c_armor.json, nocts_cata_mod_DDA/Surv_help/c_materials.json
* Removed now-obsolete helmet-compat flag.
* Added padded flag to relevant items.
* Added soft boolean to superalloy composite.
=> Armor updates for DDA version

nocts_cata_mod_DDA/Surv_help/c_armor.json, nocts_cata_mod_DDA/Surv_help/c_tools.json, nocts_cata_mod_DDA/Weapons/c_ranged.json
Easy enough ammo_scale updates.
=> Transforming item fixes for DDA version

nocts_cata_mod_DDA/Surv_help/c_materials.json
Due to https://github.com/CleverRaven/Cataclysm-DDA/pull/60607
=> Fix energy values in DDA version

nocts_cata_mod_DDA/Vehicles/c_vehicle_parts.json
The `FOLDABLE` flag has become obsolete.
https://github.com/CleverRaven/Cataclysm-DDA/pull/61072
=> Nofoldable

nocts_cata_mod_DDA/Surv_help/c_armor.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/61139 removed ´CLIMATE_CONTROL´.
=> CLIMATE_CONTROL was removed.

nocts_cata_mod_BN/Recipe/c_recipes.json, nocts_cata_mod_BN/Surv_help/c_tools.json, nocts_cata_mod_DDA/Recipe/c_recipes.json, nocts_cata_mod_DDA/Surv_help/c_tools.json
1. Updated booklearns for makeshift thermal lance, as I forgot to tweak them after lowering the difficulty.
2. Updated booklearns for makeshift greatsword, same deal.
3. Added makeshift wire saw, as a craftable source of level-1 metal sawing.
=> Update booklearns, add a tool

nocts_cata_mod_DDA/Recipe/c_recipes.json
Follow-up from https://github.com/CleverRaven/Cataclysm-DDA/pull/62517
=> Add welding kit to recipes

nocts_cata_mod_BN/Surv_help/c_armor.json, nocts_cata_mod_BN/Surv_help/c_tools.json
Been meaning to do this after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2284 was merged and forgot to until now. I'll also want to set aside a separate PR for a pending fix to perpetual powergen bionics that will allow Atomic Battery to be a bit less wonky.
=> Recharging relic update for BN version

nocts_cata_mod_BN/Surv_help/c_tools.json
BN version of https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/473
=> Integer to string for BN version of cookbook too

nocts_cata_mod_DDA/Surv_help/c_martialartsbook.json
=> fix "takes 0s to train with manuals"

nocts_cata_mod_DDA/Vehicles/c_vehicles.json
Couple of fixes to Survivor's Militarized RV.
lit_aisle and folding_bicycle changed with appropriate aisle_horizontal&aisle_lights;folded_bicycle
=> Couple fixes

nocts_cata_mod_DDA/Recipe/c_recipes.json, nocts_cata_mod_DDA/Vehicles/c_carts.json, nocts_cata_mod_DDA/Vehicles/c_vehicle_parts.json
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/502
=> Fix for DDA version

nocts_cata_mod_BN/Surv_help/c_bionics.json
Draft set aside for another in-progress PR over in BN, to be merged after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1705 is merged.
~~Turns out I never removed `BIONIC_NPC_USABLE` from the ones in Arcana so didn't need to re-add them over there hecc~~
=> Pending BN Updates: Bionic Weapon Fixes

nocts_cata_mod_DDA/Char_creation/c_classes_bw.json, nocts_cata_mod_DDA/Surv_help/c_item_groups.json
Fixes stuff broken by https://github.com/CleverRaven/Cataclysm-DDA/pull/65077
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/512
=> More fixes for DDA version

nocts_cata_mod_DDA/Surv_help/c_armor.json
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/514
=> Fix DDA version of survivor leg rig

nocts_cata_mod_BN/Char_creation/c_scenarios.json, nocts_cata_mod_DDA/Char_creation/c_scenarios.json
* Went ahead and added the main-series bio-weapons (Alpha, Beta, Delta, and Gamma) to the Experiment, Next Summer, and Ambushed scenarios. The first one on the basis that this could imply a bio-weapon character who was released from the lab and wandered off earlier on, the latter two being post-cata scenarios and thus implying one that's survived alone for a while.
* Also added Post-Human Combatives style to Next Summer, Ambushed, and Lab Patient scenarios.
=> Scenario addition stuff

nocts_cata_mod_BN/Char_creation/c_classes_bw.json
Another update related to something in BN, this time for https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2686
Unlike the previous update this does hinge on something in the PR itself, the Military Remnant trait, so will stay as a draft for now until it's all ready.
=> Pending BN Update: Necropolis Update 2

nocts_cata_mod_BN/Monsters/c_species.json, nocts_cata_mod_BN/c_achievements.json
For when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2720 is merged, updates on-kill achievement and adds names to monster species.
=> Pending BN update: species JSON includes name, achievement update

nocts_cata_mod_DDA/Surv_help/c_comestibles.json
More stuff caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/60885 but at least this one isn't too tedious to fix.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/545
=> Another minor DDA fix

nocts_cata_mod_BN/Char_creation/c_classes_r.json, nocts_cata_mod_BN/Recipe/c_recipes.json, nocts_cata_mod_BN/Surv_help/c_armor.json, nocts_cata_mod_BN/Surv_help/c_item_groups.json, nocts_cata_mod_BN/Surv_help/c_tools.json
Changelog:
-Made the paracord bracelet match the whistle mutiltool more
-Added dress pants
-Fixed new bikini parts' flags
-Removed duplicate bionic entry
=> Misc Updates

nocts_cata_mod_BN/Weapons/c_ranged.json, nocts_cata_mod_DDA/Weapons/c_ranged.json
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/577
=> Fix missing burst size for 7.62x54mmR GPMG

nocts_cata_mod_BN/Terrain/Unknown_Lab.json
Turns out I forgot one small consequence of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3967
=> Lil BN fix

nocts_cata_mod_BN/Recipe/c_recipes.json, nocts_cata_mod_BN/Recipe/c_uncraft.json, nocts_cata_mod_DDA/Recipe/c_recipes.json, nocts_cata_mod_DDA/Recipe/c_uncraft.json
1. Moved uncrafts out of c_recipes.json and into a separate file for them.
2. Added uncrafts for the flavor underwear items that are too small to be salvaged.
=> Uncraft updates

nocts_cata_mod_DDA/Mutations/c_bio_mutation.json, nocts_cata_mod_DDA/Mutations/c_bio_mutation_super_soldier.json, nocts_cata_mod_DDA/Surv_help/c_armor.json
CDDA removed these mutation values in favor of enchantments.  Ported them over
=> Port mutation values to enchantments

nocts_cata_mod_DDA/Mutations/c_bio_mutation.json, nocts_cata_mod_DDA/Mutations/c_bio_mutation_super_soldier.json, nocts_cata_mod_DDA/Surv_help/c_armor.json
Like the title says, updates to match changes in https://github.com/CleverRaven/Cataclysm-DDA/pull/72173 and https://github.com/CleverRaven/Cataclysm-DDA/pull/72106
=> Update modifiers to enchantments to match upstream changes

nocts_cata_mod_DDA/Terrain/overmap_special.json
=> Make commandcenter and final lab GLOBALLY_UNIQUE.

nocts_cata_mod_DDA/Npc/c_mission_def.json, nocts_cata_mod_DDA/Terrain/overmap_special.json
=> Maybe fix my own hubris

nocts_cata_mod_DDA/Terrain/overmap_special.json
=> "forest_thick" doesn't actually exist.

nocts_cata_mod_BN/Recipe/c_recipes.json
Bit belatedly, forgot that a while back hydrogen sacs were added to BN too, so added the relevant hydrogen recipe to the BN version.
Later on it's planned that these recipes might end up being mainlined into vanilla, plus or minus some reworks, will see tho.
=> Add alternate hydrogen recipe to BN version

nocts_cata_mod_DDA/Terrain/overmap_special.json
Fixes overmap special flag breakage caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/74290
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/623
=> Fix DDA version

nocts_cata_mod_DDA/Surv_help/c_tools.json
=> Remove HAMMER use action from items

nocts_cata_mod_DDA/Monsters/c_monsters.json
Fixes monsterflags changed by https://github.com/CleverRaven/Cataclysm-DDA/pull/74322
=> DDA update

nocts_cata_mod_BN/Surv_help/c_tools.json, nocts_cata_mod_DDA/Surv_help/c_tools.json
Easy lil fix, discovered while testing https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5283
=> Fixes solar firestarter not having `FIRESTARTER` flag.

nocts_cata_mod_BN/Surv_help/c_tools.json
Done since being allowed in BN via https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5348
=> Allow repairing budget steel with can forge in BN version

nocts_cata_mod_BN/Surv_help/c_books.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5698 is merged, adds new item flag to the relevant items.
=> Pending BN Update: `SNIPPET_NEEDS_LITERACY` flag

nocts_cata_mod_BN/Surv_help/c_books.json
=> fixed missing comma

nocts_cata_mod_DDA/Surv_help/c_armor.json, nocts_cata_mod_DDA/Terrain/c_terrain.json
- updates bash damage enchant to new syntax
- replaces symbol with #
=> [DDA] more updates

nocts_cata_mod_DDA/Surv_help/c_armor.json
DDA Moved armor enchants to incoming damage mod
=> Adjust armor enchant

nocts_cata_mod_DDA/Char_creation/c_scenarios.json, nocts_cata_mod_DDA/Surv_help/c_comestibles.json
https://github.com/CleverRaven/Cataclysm-DDA/commit/ab5cc8cf4ff70cfa6858089db4fe1e9b7358f7ca
=> Conversion of nutrition to calories (kcal)

nocts_cata_mod_DDA/Terrain/Survivor_Encampments.json
Fix #686 & #687
Seems ammo_reloaded doesn't exist anymore. RIP
=> Fix #686 & #687

nocts_cata_mod_DDA/Terrain/Bio_Weapon_Lab.json, nocts_cata_mod_DDA/Terrain/Mapgen_Variants.json, nocts_cata_mod_DDA/Terrain/Plain_Slaughter.json, nocts_cata_mod_DDA/Terrain/Surv_Camp.json, nocts_cata_mod_DDA/Terrain/Survivor_Encampments.json, nocts_cata_mod_DDA/Terrain/Survivor_Holdout.json, nocts_cata_mod_DDA/Terrain/Unknown_Lab.json, nocts_cata_mod_DDA/Terrain/forest_slaughter.json, nocts_cata_mod_DDA/Terrain/makeshift_command_center.json, nocts_cata_mod_DDA/Terrain/sketchy_cabin.json, nocts_cata_mod_DDA/legacy.json
item type and group changes, "method" function removed from mapgen and also "add" function change to "place_item".
=> Updates to make it work with DDA exp 2025-05-24-1941
