- Recipe/c_recipes.json
- Weapons/c_ammo.json
* Makes it actually more accurate, as intended. Also gave it more recoil, though this doesn't do much for game balance given most flintlock guns in the game are single-shot.
* Implemented copy-from to futureproof stuff.
* Changed recipe to be consistent with how current flintlock ammo is set up. Also made it use more lead, based off some poking around trying to get data on Minié ball loads along with trying to figure out what the hell the in-game flintlock even is (my money's on a .69, more likely to be a musket than a rifle) using weaponized math.
> Changes to Minié ball ammo

- Npc/c_mission_def.json
- Recipe/c_recipes.json
* Set quest origins back to secondary, after discussion and testing with Noct. Secondary is used for individual-specific quests, opener is used by the starter NPC, and "any" is for dynamic NPCs. Couldn't replicate the bug that led to borking it.
* Set recipes that involve welding goggles to call for glare quality rather than calling for goggles as a tool.
* Also removed the superflous quality amounts in recipes. Only required if you're telling it to use more than one source of a crafting quality.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/6
> Assorted fixes

- Surv_help/c_armor.json
Something I forgot in last PR, per @BorkBorkGoesTheCode's suggestion. Reasonably certain kevlar/steel is his recommended materials to use in the heavy military suit, though unsure what the final thickness should be.
> Change material of heavy suit

- Char_creation/c_scenarios.json
Changes in [24484](https://github.com/CleverRaven/Cataclysm-DDA/pull/24484) made removal of this scenario necessary.
> Removed Last Gig Scenario

- Npc/TALK_BFF.json
- Npc/TALK_BHUNTER.json
- Npc/TALK_BIO_1.json
- Npc/TALK_BIO_2.json
- Npc/TALK_MSCI.json
* Minor text improvements in BFF conversation.
* Reworked Evelyn Rose's dialogue to make much more use of response conditions. Now the player can only claim to be a bio-weapon if they are one (or a super-soldier), and their reponses can confirm that depending on what type they are, along with a response for if they are one
* Can oust Evelyn Rose, and doing so is easier if the player is also a super soldier of some sort. This builds on the idea that "she's a bio-weapon hunter" implies she's a similar sort as the bio-weapon hunter profession.
* Can ask about the situation, establishing the reason for the failed bio-weapons outside and the parked vehicle. Dialogue and available responses changes if the player's a failed bio-weapon.
* Added to Lambda's dialogue. She can end up giving a little …
> Major Dialogue Enhancements

- Char_creation/c_classes_bw.json
- Npc/NC_SUPER_SOLDIERS.json
- Recipe/c_recipes.json
* Couple random items for Evelynn Rose to hand out instead of her
fucking gun, along with a backpack to ensure she can carry it.
* Allow breaking apart bio-weapon badges into silver.
* Downgraded Alphas's Apex Predator to Hunter, as the intelligence
penalty has weird effects in character generation.
* Removed Chaos threshold for UI reasons, after confirming it still
permits starting with Eater of The Dead without it. Leaving the fungal
failed bio-weapon with Mycus is both fine UI-wise and vital, as it makes
sense for Mycus to override that, plus it needs the threshold to
function.
* Replaced Gamma's Very Smart mutation with Bookworm, as the int bonus
likewise has weird effects if you switch professions during chargen.
> Minor improvements

- Recipe/c_recipes.json
- Surv_help/c_bionics.json
- Terrain/makeshift_command_center.json
* Fixed bio-weapon badges turning into nothing when uncrafted. Turns out
that that feature doesn't work despite it being used, and for all I know
it may have never worked.
* Some changes to itemgroup spawns in the makeshift command center, as
varible-repeat is now WAY less predictable. Oughta fix up the other
locations sometime.
* Replaced the command center's indoor charcoal smoker with a pair
outdoors, as using it for non-recipe smoking indoors is a Bad Idea.
* Moved that one guard a step down so they aren't in the middle of the
walking path.
* Rebalanced and reworded the laser gatling gun, because sadly "takes up
an arm" is hardcoded into the fusion blaster arm. Main effects are
reducing cost to 50 and burst size to 50, sae as fusion blaster (which
has more damag). Power per activation …
> Assorted changes

- Monsters/c_monsters.json
- Npc/c_npc.json
- Terrain/Bio_Weapon_Lab.json
* Reduced odds of gladiator NPCs running off in random directions.
* Set it so that random prepper NPCs will run towards you to talk instead of fucking off in a random direction, closer to the behavior of dynamic NPCs.
* Set prepper default talk topic to TALK_STRANGER_NEUTRAL instead of TALK_SHELTER, since only a handful of them really have shelter, plus "Hello there." makes more sense for an NPC that now actively tries to greet you.
* Changed some fridges in the bio-weapon lab to lockers, the ones holding non-food stuff.
* Removed some redundant uses of "repeat 1" for bio-weapon lab item spawns.
* Further rebalanced some problematic use of variable repeat in bio-weapon lab.
* Implemented the idea Noct and I discussed of making zombie super soldiers not revive, since they drop their …
> Updates for bio-weapon lab, NPCs, and zombie super soldiers

- Npc/TALK_BHUNTER.json
- Npc/TALK_BIO_1.json
- Npc/TALK_BIO_2.json
- Npc/TALK_MSCI.json
* Changed TALK_MISSION_OFFER to TALK_MISSION_LIST, fixing weirdness that happens when asking about a mission after completing them.
* Also fixed Lambda having no dialogue and Sigma having redundant dialogue due to talk ID duping.
> Dialogue and mission fixes

- Monsters/c_monsters.json
* Was a cute idea when I added it, but not really needed, and have already had one person confused by it.
If I cold set custom death messages, and if there was also a very smol death explosion effect available, I'd do that...
> Removes smol flavor splatter

- Surv_help/c_item_groups.json
* Extensively rebalances how common Rebuilding Civilization is. Adds a shot at encountering the advanced books to `mansion_bookcase` as suggested in the relevent issue, while likewise grouping the placement of basic-tier Rebuilding Civilization into a single group that the groups can likewise call as a possible result, allowing for rarity to be tweaked without running into the fact that a book for every skill enofrces a high minimum weight.
* Made it so that basic book itemgroups will sometimes have basic Rebuilding Civilization books, while made the rare ones sometimes in prepper locations (in addition to mansions).
* Shifted around the widespread appearances of hand-drawn map, making them most common in labs rather than common bedrooms, and also showing up in prepper/survivalist …
> Itemgroup alterations

- Monsters/c_monsters.json
Made changes to the super soldiers to be more "smart". Precursor to #45 
The super soldiers will start ignoring the player until their anger conditions are met. For all but the juggernaut that is to be hurt or have their friends hurt or killed; for the former it is to simply be close to the thing. They were given very limited pathfinding, with the BAMRU given the most advance one. All but juggernaut will go docile when the player is weak. BAMRU has night vision so beware of it; you can see it in the dark but so can it see you! Armor and melee capabilities adjusted to match that of zombie soldiers and bio-operators. Gun range attacks adjusted to give more leeway for guns to be use but won't be used until the zombie is actually hostile.
> Rebalance of Super Soldier Zombie Faction.

- Npc/c_mission_def.json
* Implements reveal and mark for the Command Center and Unknown Lab quests, no longer requiring the maps to find them. For now the map items have been retained, as a fallback and for players playing without NPCs enabled. May or may not dummy them out later on.
* Altered dialogue some to account for the fact that the map items are no longer vital to finding the locations.
* Added a bit of actual advice to Evy's quest advice.
I've been meaning to mess with Sigma and Lambda to maybe give them secondary quests of some sort, and/or tie their quests in with having the "kill Apophis" mission already active, but things keep distracting me from doing so.
> Updates main quest line

- Char_creation/c_classes_bw.json
- Monsters/c_monsters.json
- Surv_help/c_item_groups.json
- legacy.json
1. Fixed error message causes by zombie super juggernauts trying to fire a gun with the wrong ID.
2. Also fixes migration errors caused when loading a save without Cata++ after having loaded a save with said mod.
3. Made UPS access consistent between super soldier professions and the CBM harvests for zombie super soldiers. This means that super soldier players can now all start off able to use their weapon. NPCs still use an advanced UPS however, as I don't yet know whether trying to start them with a UPS bionic will work right.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/76
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/75
> Fix two error messages, bionic consistency

- Npc/TALK_MSCI.json
- Npc/c_effect_npc.json
- Npc/c_mission_def.json
- Terrain/makeshift_command_center.json
1. Smol fix of terrain under the smoking racks.
2. Fixed Router's post-quest dialogue showing up early.
Now the latter especially works as intended, correctly only opening up if the player started the quest then completed it (there's technically no way to fail the mission barring death, which puts missions in limbo anyway).
> Two command center fixes

- Char_creation/c_classes_bw.json
* Gave Beta Joint Torsion Ratchet as a backup power source.
* Changed Gamma's Joint Torsion Ratchet for Battery System.
* Gave Delta Ethanol Burner as a backup to Internal Furnace.
* Gave super soldier B.A.M.R.U. Battery System instead of Joint Torsion Ratchet.
General idea is this gives each of the bio-weapons two different power systems, one primary and one secondary (Alpha's backup method being Heat Drain, as MI is pretty much the only power source that's still practical in almost all situations).
Likewise, this also makes the super solider professions each use a different power system that references how the specific versions match up with one of the bio-weapons, with the standard super soldier being the odd one out due to not taking after Alpha.
> Update bio-weapon power sources

- Vehicles/c_vehicle_parts.json
Seems that self copy-from for vehicleparts breaks some intended behavior, plus the apparent change making these parts foldable seems to not be utilized in any vehicles at present (as none of the relevent vehicles added would be foldable anyway).
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/82
> Remove self-copy-from vehicle parts

- Npc/TALK_MSCI.json
* Fixes the syntax that no longer works. In fact the way I set Router to update his dialogue was kinda clunky and was completely unrelated to ANOTHER area of dialogue where post-mission dialogue changes, so I implemented a less-fucky dynamic line that's more closely related to how the player passes information from Router to Sigma and Lamba.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/87
This feature would be so much easier if I had a way for mission completion to cite the same dialogue effects that mission starts can...
> Dialouge fixes part 2

- Recipe/c_recipes.json
Simple update to make the charcoal output, material demand, and time consumed more consistent with vanilla's item-based charcoal production. Now takes 2 volume of material, producing 10 charges in 20 minutes (2 minute increase relative to 5% of a lit charcoal kiln's burn time).
As a consequence, while sticks and two-by-fours are no longer used, it instead allows all of the other low-volume items accepted for filling a charcoal kiln, including splintered wood.
> Updates charcoal recipe to be consistent with vanilla

- Weapons/c_ranged.json
- Weapons/c_ranged_override.json
Someone on the Cataclysm DDA Discord mentioned that guns don't take shoulder straps, so I decided to fix that. 
The guns didn't have shoulder straps slots because they were not updated to reflect the changes of [#28757](https://github.com/CleverRaven/Cataclysm-DDA/pull/28757/), so I added the "sling" slot to guns that took accessories.
I accidentally made the PR on my master branch, but  it's more trouble than it's worth to fix that.
> Add a slot for shoulder strap to all guns with accessory slots

- Npc/c_mission_def.json
Turns out the old outdated missions that were dummied out were THAT old, they caused some load errors. Could've just removed them but went ahead and gave them an update to fix it for now.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/94
> Update dummied-out missions

- Monsters/c_monster_drops.json
- Npc/NC_SUPER_SOLDIERS.json
- Surv_help/c_item_groups.json
- Weapons/c_ranged.json
Thanks to @jmattspartacus for finding the cause of the bug this fixes.
* Overhauled the fancy laser weapons once again. Now they use atomic batteries instead of UPS, as a properly-functional version of the older "use plutonium cells outright" idea Noct had.
* Also rebalanced the Omnitech laser weapons to use variously FIRE_20 (I only just now learned that's a thing), FIRE_50, or FIRE_100. In addition they make use of reload time now (generally slower than changing a mag for mundane guns), with description tweaks to mention the change, and removal of some properties that were just setting the default 0.
* Set the NPCs that had UPS weapons to now use the right sorts of atomic-powered versions of the weapon, and have the right sorts of cells on hand.
* Because it turns out that neither the …
> Update battery items and weaponry

- Char_creation/c_classes_bw.json
- Monsters/c_monster_drops.json
- Surv_help/c_item_groups.json
- Surv_help/c_spells.json
- Surv_help/c_tools.json
- Terrain/Unknown_Lab.json
This is an item idea that the spell system has finally made possible, via both items able to cast spells and via a spell being able to charge CBM power, as a way to deal with the fact that CBMs have been getting fewer and fewer powergen options. Eventually minireactor CBM will likely stop working, so...
* Implemented the CBM induction charger. Wearable item meant to provide an alternative method of power at a steady rate, with some disadvantages if overused. Uses artifact charging properties to simulate RTG power generation (over time), and its spell-based `use_action` provides a proper conversion of 1 hour's worth of charging into a given amount of bionic power.
* Gave the item to Bio-Weapon Beta and the super soldier juggernaut professions, in return removed their reactor CBM and …
> Implement RTG CBM inductor item

- Monsters/c_monstergroups.json
* Pushes back entry of zombie failed bio-weapons a day after the cataclysm. Idea is that attrition rate builds up soon after Apopis' plan goes into action, but failed bio-weapons remain an active presence since day one.
* Pushes arrival of fungal failed bio-weapons back 2 days, except for fungal monstergroups. Contact with the Mycus probably happens reasonably often, but filtration back into general population might be slower. Main reason they're still a day-one presence in fungal turf however is I dunno if pushing them back a couple days will cause any weird behavior when combined with No Fungal Monsters mod.
* Pushed zombie super soldiers back 3 days. Main idea was that, in addition to giving the player some time to prepare and make day-one scouts no longer a thing, they also might …
> Staggered monstergroup additions

- Vehicles/c_vehicles.json
Added the provided suggested JSON change, giving Cata++ vehicles the requisite wheel mounts now in use, replacing the older method of steerable wheels as distinct parts.
Closes #117
> Fix missing wheel mounts

- Vehicles/c_vehicle_parts.json
* Renamed the generators and added descriptions to make it a bit more clear what these parts are.
* Updated their stats to be more in line with how electric motors have been updated over the past year or so.
* Added variants for the tiny and super motors too.
A couple notes:
1. Tiny alternators are intentionally a fair bit less efficient than they would be if I just straight-up took the math for turning a motor into a dynamo, because they pretty much directly compete with motorcycle alternators.
2. Small electric dynamos are also a bit less efficient, but this is consistent with numbers that Mark suggested, based on some long-term plans for making tiny and small electric motors more power-hungry to reduce total efficiency.
3. Super electric dynamos are fucking loco. You'll need at least a …
> Update generator parts

- Surv_help/c_martialarts.json
* Overhauled the override to Bionic Combatives to use extend instead for injecting the mod-specific items to its weapons list.
* Converted bionic claws added to a few martial arts that now specify which unarmed weapons are permitted.
* Tazer blades, converted bionic knives, flesh knives, and molded knives added to styles that allow knives, especially those that allow vanilla makeshift knives.
* Converted bionic swords and biological swords added to sword-focused swords where they're reasonably close to other swords and sword-like-objects used by said styles. Notably affected by this are Medieval Swordsmanship (yaaaay at it being mainlined), and Ninjutsu that now defines its weapon list explicitly.
* Fior Di Battaglia only gets molded axe added because it allows stone axes.
* Since Krav …
> Martial Art Updates

- Surv_help/c_armor.json
- Surv_help/c_bionics.json
- Surv_help/c_effects.json
- Surv_help/c_martialarts.json
- Surv_help/c_spells.json
* Added a reversion to the active stealth cloak so it no longer vanishes when depleted.
* Updated CBM RTG Inductor to implement radiation correctly instead of acting weird.
* Updated the power cost values of the bionics to use kilojoules, since CBM power is now basically straight kJ. Only the cost of deploying the bionic sword is actually affected by WIP changes, currently.
* Couple typo fixes.
Costs for bionics are nonetheless informed by work being done in https://github.com/CleverRaven/Cataclysm-DDA/pull/34456, with thanks to @RDru. Not sure yet what the final costs will be, but they seem reasonable so Noct and I likely won't have to chance much on Cata++'s end. The ridiculously-high deployment cost for CBM weapons always struck me as odd...
Also closes …
> Fix stealth cloak, typo fixes

- Char_creation/c_classes_bw.json
This is at least an interesting option that's easier to make use of than the hacky artifact method the RTG CBM inductor relies on. Item remains existent for now, as it does have some interesting uses.
Was pondering whether I could devise any other CBMs to add, ideally to make Delta's powergen setpup more unique, but nothing good game to mind...
> Gives Beta gasoline cell instead of RTG inducer

- Npc/NC_BIO_WEAPONS.json
- Npc/NC_SUPER_SOLDIERS.json
This removes bayonets and shoulder straps from Evy, Lambda, Sigma, and the super soldier NPCs. A little more testing revealed that it's not strictly necessary to remove the shoulder strap, but I'd rather be thorough and this prevents any inevitable issues that might come 
For a bit of context, the bayonets were a holdover from the brief period when I was able to get the NPCs to successfully use UPS laser weapons, which mandated adding a bayonet or else their AI would refuse to acknowledge actually having a gun in their hands. When that had to be undone because UPS weapons started just plain crashing when used by NPCs in general, I left the gunmods on figuring it wouldn't hurt.
I did leave the shoulder straps intact for the player versions of the super soldiers however, but might later on …
> Remove bonus gunmods from Evy and other NPCs

- Surv_help/c_snippets.json
This turns the small JSON into the big JSON.
Fixes skippable error messages that only show up when a note citing the snippet tries to ping the ones added by mods, and suddenly notices they don't need IDs (which are now mandatory).
> Implement snippet IDs

- Surv_help/c_martialarts.json
- Surv_help/c_techniques.json
`You learned how to handle yourself in the cataclysm.  Whether armed or unarmed, you know how to use your wits to stay alive.  Survival is of the highest priority.`
Name | Level Available | Type | Effect
------------ | ------------- | ------------- | -------------
Arm Block | Melee 2 |  | 
Leg Block | Melee 8 |  | 
Elusiveness | Melee 4 | Unarmed/Melee Onmove Buff | +2 Dodges, Dodge Skill increased by 50% of Intelligence, knockdown immunity. Lasts 1 turn.
Active Defense | Melee 5 | Unarmed/Melee Onhit Buff | +2 Blocks, damage blocked increased by 75% of Intelligence. Lasts 2 turns.
Misdirection | Melee 6 | Unarmed/Melee Onkill Buff | +2 Dodges, +2 Blocks, speed increased by 100% of Intelligence, stealthy movement. Lasts 3 turns.
Grab Break | Melee 7 | Unarmed/Melee Defensive Tech | Grab …
> [WIP] Overhaul for Survivor Combatives

- Surv_help/c_martialarts.json
- Surv_help/c_techniques.json
Implemented some suggestions that came up in DMs with Hymore, sadly after the initial overhaul was merged.
* Re-implemented gaining limb blocks with armor CBMs, as Hymore confirmed that the UI override is just a display issue, you can have both "blocks at level X" alongside "blocks with this CBM"
* Halved the bonus blocks and dodges of Elusiveness and Active Defense.
* Reduced Int scaling of the dodge skill bonus from Elusiveness.
* Increased Int scaling of the damage blocked bonus from Active Defense.
* Doubled duration of Misdirection.
* Gave the counter-attacks reduced damage, like what Dragon Kung-fu gets (in this case due to allowing weapons, instead of being a stronks-based style).
> Proposed changes to Survivor Combatives

- Surv_help/c_martialarts.json
Noticed I forgot to give it melee as its primary learning skill, when it uses melee a lot more than unarmed. Easy enough to change.
> Fix Survivor Combatives not learning off melee

- Monsters/c_monster_harvest.json
- Terrain/Bio_Weapon_Lab.json
- Terrain/Unknown_Lab.json
- Terrain/makeshift_command_center.json
- Terrain/sketchy_cabin.json
- Vehicles/c_carts.json
* Updated harvest entries for bionic monsters. Now CBMs are harvested already deployed and non-sterile. They also return filthy for zombie failed bio-weapons and zombie super soldiers, but are merely non-sterile for regular failed bio-weapons and Apophis.
* Added autoclave carts in certain locations, mainly ones expected to be harvesting CBMs from corpses. That includes all the main bio-weapon-linked locations, and the recovery/disposal room of the underground arena complex. The !!science!! variant of survivor encampment is excluded since they most likely dealt with commercially-available CBMs instead.
* Also smol lint of affected files.
> Harvest and autoclave updates

- Monsters/c_monster_harvest.json
- Monsters/c_monsters.json
- Recipe/c_recipes.json
* Implemented the new variable regen instead of the now-unused regeneration flags. On the plus side, this means now the super soldiers and bio-weapons can all get varying levels of regen.
* Updated harvest entries so that bio-weapons make use of mutant humanoid meat and fat, along with large human stomachs (forgot that was a thing).
* Removed overrides for mutagen as mutagen crafting has been extensively updated since then, and it was now causing load errors.
* Changed the welding goggles recipe to an alternative version using suffix, so it's no longer a full override.
* Converted disassembly recipes to uncrafts.
Todo: re-add variant recipes for the category serums that were tweaked (alpha, elf-a, chimera, raptor) via suffix, possibly using the organic infusor.
> Updates to regen, harvest, recipes

- Recipe/c_recipes.json
- Surv_help/c_tools.json
* Re-added alternative recipes for the advanced serums, with some updates. Their material costs now reference the old recipes to some extent, but the primary change is around standardizing the tool requirements to revolve around using the organic infuser and diffuser.
* Couple fixes to tools using arti-effects, so they show as tools instead of artifacts in the inventory menu.
* Small rename/typofix for the blood purifier. Diffusion seems like the intended word?
> Mutagenic updates, re-added recipes

- Monsters/c_monsters.json
* Shifted some of Apophis' damage from standard melee to more cutting damage.
* Set it so failed bio-weapons and zombie super juggernauts can push vehicles around.
* Set it so that zombie and fungal bio-weapons, and zombie super juggernauts, will push monsters around. Regular bio-weapons for now only got PUSH_VEH added.
* Removed GROUP_BASH from non-zombified bio-weapons and Apophis, as they're already strong enough to have decent impact on the terrain in the Unknown Lab individually.
* Likewise removed DESTROYS from Apophis, his smash strength is way up there on its own.
* Shuffled around the special attacks of zombie super soldiers a bit, and added a wider variety to them. Bio-op takedown now goes to the more nimble regular versions and scouts, smash is now primarily the juggernaut's …
> Monster flag and attack tweaks

- Npc/TALK_MSCI.json
- Npc/c_mission_def.json
* Set it up so that Router is skeptical of players who don't have a bio-weapon badge on hand, allowing the potential for a side mission that lets players find the bio-weapon lab if they've reached the command center first.
* Players who started Evy's mission first can opt to skip this, as that's the only way for the game to easily track that the player already has visited the bio-weapon lab. Sadly, it's not available to players who recruited Evy in a save predating this PR, but it's a start at least.
* Bio-weapons and super soldiers likewise outright skip the side mission, as does any player who already has a bio-weapon badge on hand.
Next part will be adding a bit more mission-wise to Router, via adding another mission before the "go kill Apophis" one. For now this sets up the framework …
> Fleshing out Router's missions: part one

- Char_creation/c_classes_bw.json
- Char_creation/c_scenarios.json
Originally was meant to have them start in armory of labs. This should work as a place holder. Might move them to sewer labs eventually but ultimate goal is give them their own starting location like bio-weapons have.
> Create scenario for super soldiers

- Char_creation/c_scenarios.json
- Monsters/c_monstergroups.json
* Allows super soldier professions to appear in the Overrun scenario.
* Also adds spawns of unevolved zombie super soldiers at the expected low weights and typical delay, for the military base's zed population.
> Adds super soldiers to Overrun scenario

- Surv_help/c_effects.json
- Surv_help/c_spells.json
- Weapons/c_melee.json
Well, I was gonna do this a while back but stuff came up, then I was planning to make this a "part zero" only porting over the essential file changes that future additions would use. Then however, as my list of "hey wait I can still change this without the bug coming into play" changes got longer, I realized that the active biological sword's fake AEA hack had already been removed some unknown time ago. This eliminated my main reason to deferring those changes: I didn't want to replace a working (if hacky) mechanic with a better one that won't trigger due to a bug. But with no AEA stuff being the norm already, I can put it in and make sure it'll automatically do what it's supposed to do when the bug is fixed.
* Added custom adrenaline effect for the biological weapons to make use of. …
> Overhaul Biological Weapons: Part One

- Char_creation/c_classes_bw.json
- Char_creation/c_scenarios.json
* Increased point cost of failed bio-weapon profession to 4.
* Added failed bio-weapons to Bio-Weapon Lab, Experiment, and Lab Patient scenarios. The latter two allow a degree more variation in traits since they aren't under the tightly-controlled conditions of the
Bio-Weapon Lab scenario.
* Slight tweak to failed bio-weapon's profession description.
> Failed Bio-Weapon Usage

- Recipe/c_recipes.json
- Surv_help/c_tools.json
Fairly simple idea that came to mind, an improvised thermal lance. Seemed more fitting in Cata++ specifically. Principle relies on a metal tube connected to an oxygen supply. When provided with an initial source of sufficient heat (magnesium ignition in this case, IRL steel wool would work too but that doesn't exist in the game yet) the metal forming the lance itself provides a source of pyrophoric material to keep the reaction going.
Item has limited charges and can double as a makeshift welder (WELD quality 1), but obviously its primary focus is cutting metal terrain, as with oxy-ace torches in the game. Also provides an additional use for oxygen packs/tanks, of course. Overall use is about half that of a small welding tank (30 charges vs 60).
> Makeshift thermal lance

- Monsters/c_monster_override.json
- Monsters/c_monsters.json
- Monsters/c_species.json
- Mutations/c_bio_mutation.json
* Updated augmented abominations to be on the very edge of hostility. Makes them still noticeably more hostile than undead augmented abominations, starting at Tracking instead of Ignoring.
* Added an anger_relations property to the failed bio-weapon profession. This gives them more leeway around augmented abominations due to being one of them, but the monster version will still rapidly figure out that the PC is a renegade and turn hostile accordingly.
* Added some unique benefits to each of the four main bio-weapon professions, defined in their genetic marker mutations. Alpha gains a benefit to max HP the more they keep their ravenous hunger at bay plus a minor impact on dodging, Beta gains a boost to stamina regeneration plus bleed resist to facilitate a sustained fight, Delta gains …
> Features/updates for bio-weapon characters

- Recipe/c_recipes.json
- Surv_help/c_tools.json
* Allowed canisters, clay canisters, and ember carriers to be used for making small batches of charcoal. Goes along with a chance in MST Extra allowing clay ember carriers to substitute for clay canisters.
* Allowed solar torches to substitute for normal torches, goes along with an arcana recipe using lit torches.
> Minor mod-compatability: tool usage

- Weapons/c_ranged.json
* Overhauled the artifact properties of the biological weapons. Stat boots now debuff strength and dexterity a bit in exchange for that +4 perception, has `AEP_SICK` and `AEP_SCHIZO` when carried, `AEP_EVIL` and `AEP_PSYHIELD` when wielded.
* Ammo flags used have been shuffled around, making all of them mild incendiary plasma weapons when used, with the advanced versions becoming more fiery, using napalm/stream effects differently, etc. Also converted the main damage to a pierce damage block, with a note to switch from armor_multiplier to proper pierce once the PR for that is in (post-0.E).
* Every biological ranged weapon except the pistol also can grant the bloodlust adrenaline surge effect when you get hit. Unlike with the biological sword, the lack of transform means it won't be …
> Biological Weapon Updates, Part Two

- Terrain/Survivor_Holdout.json
- Terrain/mapgen_obsolete.json
- Vehicles/c_vehicle_groups.json
- Vehicles/c_vehicles.json
* Changed ID "surv_rv" to "c_surv_rv_military" due to https://github.com/CleverRaven/Cataclysm-DDA/pull/38927 using the same ID in their newer vehicle addition.
* Also renamed the Survivior's RV to "Survivor's Militarized RV" to ensue clarity.
Tested to ensure that this wouldn't break old saves.
The ID and name made me suspect it was copied from Cata++ at first, but with visual comparison it's easier to tell that the new vehicle is a direct edit of the vanilla luxury RV, whereas the older Cata++ RV has undergone more extensive changes over time:
> Prevent Vehicle ID Conflict

- Surv_help/c_item_groups.json
- Terrain/Bio_Weapon_Lab.json
- Terrain/Unknown_Lab.json
- Terrain/mapgen_obsolete.json
* Replaces all Cata++ spawns of now-removed `anesthesia` with the newer`anesthetic_kit`.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/182
Old saves that have existing instances of this item *might* still break because I'm not sure if they implemented migration entries.
> Update references to obsoleted anesthesia item

- Char_creation/c_scenarios.json
- Char_creation/c_start_locations.json
Simple enough, they changed `ident` to `id`, `target` to `terrain`, and changed the IDs of every vanilla starting location... :/
> Fix starting locations

- Recipe/c_recipes.json
- Recipe/c_requirements.json
- Surv_help/c_tools.json
* Updated use of metal molding requirement to only specify the mold items and hammering quality, allowing the use of steel_standard or steel_tiny as needed. And crafting mechanics mean that max charges in the can forge no longer actually blocks crafting, it merely requires a
couple reloads.
* Reworked bearing recipe with the latest update to bearing crafting in mind.
* Reworked time for a few molding recipes. Basically the gist is 30 minutes or 10 minutes per lump of steel used, whichever is higher (the latter seems to be how time was already determined, just the former adds a minimum time). In exchange, batch time savings are now implemented.
* Added metal-molding recipes for rebar, nails, and blades. Blade recipe is the odd one out, needing cutting quality instead of specific items as …
> Metal molding updates, and molded crowbars

- Monsters/c_monster_override.json
- Monsters/c_species.json
- Mutations/c_bio_mutation.json
* Shift anger triggers from species to the individual monster overrides, making the species overrides no longer needed.
* Added aggression overrides to those military robots, enough to still be exceedingly hostile to anything that lacks the Bio-Weapon Gamma trait.
* Reduced Gamma's anger-relation reduction so that only those altered military robots will be affected by it enough to go down to Tracking.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/188
> Alter how Gamma's perk is defined

- Monsters/c_monster_override.json
- Recipe/c_recipes.json
- Surv_help/c_override.json
Cause is https://github.com/CleverRaven/Cataclysm-DDA/pull/40695. I figured it was either this or replace all spawns of laser turrets with searchlights, but eh.
* Updated the override for laser turrets into a full copy of the monster for futureproofing reasons.
* Copied over the item definitions for the obsolete item forms as well.
* Copied over the obsoleted recipe and forcibly un-obsolete it.
Yeesh, they even stripped out part of the code so that it won't work exactly the way it used to if Aftershock tried to reclaim laser turrets...
> Copy over obsoleted monster/item stuff

- Recipe/c_recipes.json
Chances references to call for regular food and drink cans, as one of many overarching side effects of nested containers is changing the "this is sealed" feature into a property of the individual item, meaning unsealed cans as distinct items have been removed.
Fixes potential segfaults caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/41332 removing unsealed cans via migration instead of moving them to obsolete.json. Then again, maybe better to need to fix it now while the change is still fresh, than to forget about it in mods until it's eventually deleted from the obsolete file...
> Update references to obsoleted cans

- Monsters/c_monsters.json
* Removed obsolete `BLEED` flag from the only monster that used it, now that bleeding is based on raw cut/stab/bullet damage automatically.
Some minor thoughts for later:
1. Could give some effect-based removal of hypovolemia to the adrenaline surge caused by the active biological sword, but transformaing relics are still broken, plus I don't think it'll actually affect the vitamin-based blood loss so it would only prevent you from feeling the effects of shock for as long as the adrenaline surge holds out, which is a VERY brief period of time.
2. Could give IFAKs to the super soldiers?
3. Could give vitamin rate tweaks to Alpha and/or Beta that make them recover blood volume and red blood cells faster, but not sure which should get it. Alpha gets a lot of metabolism-based features that …
> Updates for blood overhaul

- Surv_help/c_spells.json
Changes use of `true` damage type to `pure` in a spell, due to yet more changes to DT IDs.
> Update damagetype again

- Surv_help/c_tools.json
HAND_EITHER caused a segfault due to invalid json. Replaced with new standard.
> Fixes segfault due to old json

- Monsters/c_monstergroups.json
- Surv_help/c_armor.json
- Surv_help/c_effects.json
- Surv_help/c_martialarts.json
- Surv_help/c_spells.json
- Surv_help/c_tools.json
During the process of making and testing a Bright Nights version of Cata++ (PR will be made after https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/214 is merged), I found some misc fixes and changes that will apply to both versions, so PRing them now.
* Set some augmented undead soldier spawns to start earlier, since they now have unevolved forms. Regular city spawsn are still heavily delayed.
* Belatedly made the scout's tool solar-powered once more.
* Updated stealth cloak's relic data to not need an explicit enchantment. Can remove the old enchant when 0.F is out, for now best to retain it for old saves.
* Reduced recharge rate of biostim and the infusors to once per hour, for consistency with the eventual BN version.
* Rebalanced biostim effect duration stuff so the hour-long …
> Assorted fixes found while preparing thr BN version

- nocts_cata_mod_BN/Vehicles/c_vehicle_parts.json
- nocts_cata_mod_DDA/Vehicles/c_vehicle_parts.json
Implemented proper install/repair/remove requirements for vehicleparts based on similar vanilla parts, removing the obsolete difficulty stat formerly used as well as the old hardcoded screwdriver/wrench flags. Fixes skippable load errors on most recent builds of DDA.
> Modernize vehicle part JSON

- nocts_cata_mod_DDA/Weapons/c_mods.json
New updates made FIRE_(number) invalid. This works exactly the same. Sorry, I don't know how to merge pull requests.
> Changed FIRE_50 with "ammo_to_fire"

- nocts_cata_mod_DDA/legacy.json
Updated the file by removing the ACS 47 stealth cloak from the legacy file and updating names for some of the items as their existence is not a bug in older versions.
> Fixes to legacy file

- nocts_cata_mod_DDA/Terrain/Unknown_Lab.json
Whoops, for some reason the DDA version (but not the BN version) was set to spawn the now-removed obsolete version of the cloak.
Easy enough to fix and test it.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/239
> Fix load error

- nocts_cata_mod_DDA/Vehicles/c_vehicle_parts.json
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/242 caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/46466 not having the sense to retain the old ID for the highest-level requirement, which would've prevented compatibility errors entirely.
Can't do anything about the problem discovered during discussion of that issue, that one's purely caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/46701 and causes a whopping 66 mandatory specials to be present in vanilla. That's something for @Venera3 to fix, I can't do anything about that.
> Update tool requirement

- nocts_cata_mod_BN/Char_creation/c_classes_bw.json
- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_BN/Surv_help/c_materials.json
- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_BN/Weapons/c_ranged_override.json
- nocts_cata_mod_BN/modinfo.json
- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Surv_help/c_materials.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
- nocts_cata_mod_DDA/Weapons/c_ranged_override.json
- nocts_cata_mod_DDA/modinfo.json
* Updated flamethrowers in the BN version to use heat-type damage now that lasers and flamethrowers were updated in BN too.
* Belatedly fixed aux pistols in the DDA version not having bullet-type damage.
* Removed the overrides to lasers since heat-type with low AP is now the standard in both DDA and BN.
* Updated all uses of `ident` to `id` now that it's standard for both DDA and BN.
> Damagetype and ident updates

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_tools.json
- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
* Added a makeshift shotgun suppressor, based on the same general principles needed for shotgun suppressors. Bit more complex to make but still low-level and disposable.
* Added a recipe for making the vanilla shotgun suppressor too, at a higher level.
* Added a makeshift autoclave made using a diesel engine and other components. I considered other ideas like a less-efficient electric version or even a steam engine variant, but power usage rapidly seemed less practical with those options. Vanilla autoclaves already seem deliberately designed to be unusable without converting unless you have an atomic battery, despite letting you load batteries that'll never offer enough power.
* Fixed survivor aux flamethrower not having pocket data in the DDA version.
> Some assorted item ideas

- nocts_cata_mod_BN/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
What was supposed to be a small set of changes to some missing things in PR #247 turned into changing various things to ensure the point cost was justified and the professions worth picking over other stuff apart form the unique dialogue and other stuff when doing NPC missions. Various things were taken into consideration like the fact you will be locked from all mutation trees since you start post-thresh in the Sentinel category, the fact the profession is dictated by the scenario choose and the fact they are for the most part filling specific niche which outside off they are no better than any other survivor. Things changed ended up being too various to list here but general idea was giving stat boost, removing irrelevant bionics and adding relevant ones, removing some items, balancing …
> Fixes plus re-rebalancing of sentinel professions

- nocts_cata_mod_DDA/Surv_help/c_armor.json
Whoops, easy enough to fix.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/252
> Fixed scout suits not covering arms in DDA version

- nocts_cata_mod_BN/Monsters/c_monstergroups_modcompat.json
- nocts_cata_mod_BN/Surv_help/c_item_groups_modcompat.json
- nocts_cata_mod_DDA/Monsters/c_monstergroups_modcompat.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups_modcompat.json
Adds monster and itemgroup entries that inject Cata++ items into certain parts of other third-party mods, in particular Arcana and PK's Rebalancing. For the latter especially, the monstergroup additions were weighted roughly to mimic the most recent known version of the PK/Cata++ monstergroup patch, which should thus render it no longer necessary.
> Mod inter-compatability additions

- nocts_cata_mod_DDA/Monsters/c_monstergroups_modcompat.json
As usual, we can't have nice things in DDA. Defining a non-overriding monstergroup for monstergroups only defined by other mods works fine in the BN version, but creates two skippable load errors in the DDA version.
Closes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/255
> Remove mod-compat monstergroups from DDA version

- nocts_cata_mod_DDA/Surv_help/c_armor.json
Based on my math, the Survivor scout suit is still 3 times as encumbering as the AEP suit, the Survivor Armored Scout is as encumbering as the ANBC suit, and both are about about 5 times as encumbering when full of items. I think this makes more sense in vanilla balance, and allows the suits to be melee viable. I look forward to hearing any sort of response to this proposal.
> Buff Encumberance on Scout Suits

- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
Turns out that the survivor's flamethrowers were treating the reload time in the same way that magazines treat reload time, despite having an internal magazine. So instead of taking a fixed 20 seconds to reload the whole thing at once, its base reload rate was 20 seconds per single unit of fuel loaded, and with it holding 1500 units of fuel...
Fixed it to be only slightly slower than reloading a vanilla pressurized fuel tank, though combined with its lower capacity it'll still work out to a comparable reload rate (and retaining the disadvantage of being unable to simply swap tanks).
> Fix weird issue with flamethowers

- nocts_cata_mod_BN/Surv_help/c_tools.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
* Fixed the scout tool not charging in the BN version due to somehow having `max_charges` removed during a previous rework.
* Fixed accidentally forgetting `NO_RELOAD` and `NO_UNLOAD` for the scout's tool in the DDA version at some point.
> Bugfixes for scout's tool

- nocts_cata_mod_BN/Monsters/c_monster_override.json
- nocts_cata_mod_BN/Monsters/c_monstergroups_modcompat.json
- nocts_cata_mod_BN/Mutations/c_bio_mutation.json
* Had to remove the PK's Rebalancing monstergroup additions from the BN version to. My guess is the game does not actually yet support injecting monsters into a monstergroup unless it actually exists, and forcing them to count as an override would most likely break if combined with PK. Minor feature anyway, so oh well.
* Removed some JSON bits specific to the DDA version I accidentally left in the BN version.
> JSON fixes for BN version

- nocts_cata_mod_BN/Npc/TALK_BHUNTER.json
- nocts_cata_mod_BN/Npc/TALK_MSCI.json
- nocts_cata_mod_BN/Npc/c_bgss.json
- nocts_cata_mod_BN/Npc/c_effect_npc.json
- nocts_cata_mod_BN/Npc/c_mission_def.json
Just an update to how the NPC dialogue effects that're meant to be permanent are applied, using the new permanent boolean.
> Update permanent effects for BN version

- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
Pushed to wrong branch originally, woops.
Alpha has padded feet, yet still spawns with foot rags, this makes no sense.
> Fix Inconsistency in Bioweapon Alpha

- nocts_cata_mod_DDA/Surv_help/c_armor.json
Reinstating the old enchantment seems to work fine, it's just that defining `ench_effects` directly in `relic_data` is evidently broken in the DDA version.
BN version seems to also work fine, most likely due to Olanti's fixes to relic code.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/274
Root cause is whatever broken code is behind https://github.com/CleverRaven/Cataclysm-DDA/issues/49334
> Fix save/load breaking stealth cloak in DDA version

- nocts_cata_mod_BN/Monsters/c_monster_drops.json
- nocts_cata_mod_BN/Monsters/c_monsters.json
- nocts_cata_mod_DDA/Monsters/c_monster_drops.json
- nocts_cata_mod_DDA/Monsters/c_monsters.json
Simple change that sets fungal augmented abominations to call a different monsterdrop itemgroup than normal abominations, allowing them to spawn a random marloss item in addition to their normal gear. Also set up so that a pending PR in Arcana can inject different anomalous drops into their drops compared to the other abominations.
Also linted affected files.
> Gives fungal augmented abominations a separate monsterdrop itemgroup

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
Changed it so that crafting nano-mutagenic serum doesn't have to eat up
charges from the plutonium batteries used as a radiation source, since
that method is buggy plus current lore is that plutonium cells aren't
powered by radiation but use it as part of superscience needed for
better power storage. So just having the cell, even a depleted one, on
hand logically should be able to provide a controlled source of
radiation.
Also changed it to allow a standard plutonium cell as an option, as well
as betavoltaic cells and RTGs. Disallowed chunks of cobalt-60 since it's
an uncontrolled source, but can re-add it (along with plutonium slurry I
guess) if anyone wants to work with uncontained radiation while making
nano-mutagenic serum.
Can maybe also revisit the other tools required, since it …
> Update radiation source needed for nano-mutagen

- nocts_cata_mod_DDA/Monsters/c_monster_override.json
- nocts_cata_mod_DDA/Monsters/c_monsters.json
- nocts_cata_mod_DDA/Surv_help/c_spells.json
- nocts_cata_mod_DDA/Terrain/Mapgen_Variants.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
* Fixed the mossberg spawn that's also since been turned into a gun variant, in the DDA version
* Updated monster death functions for monsters in the DDA version. Had to write custom monster death spells for Apophis and fungal augmented abominations, since I needed to be able to combine "explode plus leak acid" and "fungus plus leak acid"
* Also fixed missing pocket data for pneumatic LMG.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/283
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/284
Also gah, I could've sworn I created a branch instead of pushing changes into my fork's master branch. Eh.
> More fixes for DDA version

- nocts_cata_mod_DDA/Weapons/c_magazines.json
I forgot how it's supposed to define armor_data it seems, in the last fix. Odd since I could've sworn it loaded with no errors, but a comment in the commit mentioned an error cropping up somewhere. This time made sure that it loaded in, spawned in, and could be worn with no issue.
> Fix survivor ammo belts in DDA version

- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
On reworking the mi-go beam weapon during the previous PR, I made note to myself of the energy-efficiency of related weapons and determined that the survivor battery weapons could perhaps be made a bit less wasteful.
* Changed battery pistol to deal 5 damage and use 20 charges, making it exactly 25% efficient (previously 4 damage for 50 charges, or 8% efficiency).
* Changed battery rifle to deal 12 damage and use 50 charges, making it 24% efficient (previously 8 damage for 100 charges, also 8% efficiency).
This still makes them low-power in exchange for being accessible due to using household batteries, but to less of an extreme than before. Most energy weapons tend to hover in the neighborhood of 50% efficiency, the mi-beam weapon at 75%, Omnitech weapons generally at 80%, and the flesh …
> Standardized battery pistol/rifle energy efficiency

- nocts_cata_mod_BN/Npc/NC_GLADIATORS.json
- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Npc/NC_GLADIATORS.json
- nocts_cata_mod_DDA/Npc/NC_PREPPERS.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Terrain/makeshift_command_center.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Weapons/c_ranged_override.json
Updates DDA version now that https://github.com/CleverRaven/Cataclysm-DDA/pull/51309 has revealed some old obsoleted stuff.
Includes new use of acidchitin armor for Red Team in both BN and DDA versions, and yoinking the laser cannon in the DDA version.
Also allows harvesting a laser minigun CBM from Apophis instead of a fusion blaster arm since that's obsolete, which also fits with an idea I was pondering doing sometime...
> Fixes for DDA version of mod

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
Simple enough fix, realized that Cata++ was injecting traits into scenarios in a way that overrides mod injection of traits if it's lower on the load order.
Tested via loading up a world with both Arcana and Cata++, now the martial art traits from both show up in the proper scenarios such as Ambushed and The Next Summer.
> Fix injection of traits into scenarios

- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
Same deal with https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/311 as before, DDA data bein' weird and harder for smol birbs to work with.
Also gave the DDA version same armor data and pocket info as vanilla version.
> And add DDA version of the stuff

- nocts_cata_mod_BN/Surv_help/c_bionics.json
- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
Adds the right flag to the flamethrower bionic weapon, the aux flamethrower, and the ionic cannon. Survivor flamethrower will also get this automatically once the relevant PR is merged since it inherits from the flamethrower template item.
Leave it for now until is https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1004 merged, fiarly certain it'll only cause a skippable load error from citing a non-existent flag if merged early but still.
> Add PYROMANIAC_WEAPON to BN items

- nocts_cata_mod_BN/modinfo.json
- nocts_cata_mod_DDA/modinfo.json
According to 
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/doc/MODDING.md 
and 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MODDING.md
`content` category is expected to be used with such large mods as Cataclysm++, so I'm proposing this via PR.
This is a little change that will sure not break anything but will help inexperienced players to see at glance that this is a big thing.
Additionally, changed modinfo description to better describe what exactly to expect from the mod via in-game UI.
> Changing mod category from misc additions to content

- nocts_cata_mod_BN/Terrain/Plain_Slaughter.json
- nocts_cata_mod_DDA/Terrain/Plain_Slaughter.json
Easy fix, seems that recent DDA builds have only just lately started checking for this, as it appears to be an old mapgen issue that went unreported until now.
> Fix a smol error with Plain_Slaughter map

- nocts_cata_mod_BN/Recipe/c_recipes.json
Simple update due to tanned hides/pelts no longer being a thing in BN, in favor of tanning being less hassle and making leather/fur patches directly.
> Update leather usage in BN version

- nocts_cata_mod_BN/Surv_help/c_armor.json
Easy fix, just a small holdover from before the material updates were added to let them be repairable while having the exact specified armor values.
> Fix heavy military helmets in BN version

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_BN/Surv_help/c_martialarts.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Surv_help/c_martialarts.json
* Removed injection of atomic batteries into vanilla itemgroups in the BN version, since it's been implemented in vanilla BN.
* Updated the spawn injections and itemgroup setup in the DDA version to match the vanilla BN implementation.
* Removed now-excess % in martial art buff descriptions, seems to not be needed anymore.
> Couple assorted fixes

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_BN/Monsters/c_monster_drops.json
- nocts_cata_mod_BN/Mutations/c_bio_mutation.json
- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_BN/Surv_help/c_item_groups_modcompat.json
- nocts_cata_mod_BN/Surv_help/c_martialarts.json
- nocts_cata_mod_BN/Surv_help/c_martialartsbook.json
- nocts_cata_mod_BN/Surv_help/c_techniques.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Monsters/c_monster_drops.json
- nocts_cata_mod_DDA/Mutations/c_bio_mutation.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups_modcompat.json
- nocts_cata_mod_DDA/Surv_help/c_martialarts.json
- nocts_cata_mod_DDA/Surv_help/c_martialartsbook.json
- nocts_cata_mod_DDA/Surv_help/c_techniques.json
Still unsure what'd be a good name for this style that fits the "X Combatives" theme Bionic Combatives and Survivor Combatives both have, but eh.
`You've learned a number of tricks to take advantage of the potential that abandoning your humanity can offer.  Focused on heavy, powerful weapons or mutant limbs, a supernaturally strong post-human can use their abilities to great effect.`
Name | Level Available | Other Requirements | Type | Effect
------------ | ------------- | ------------- | ------------- | -------------
Large And In Charge | Melee 6 | Melee/Unarmed | Static Buff | Accuracy increased by 15% of strength, -10 move cost.
Stored Potential | Melee 5 | Melee/Unarmed | OnPause Buff | -10 move cost. Lasts 3 turns, stacks 3 times.
Bull Rush | Melee 4 | Melee/Unarmed | OnMove Buff | …
> Martial art addition, related tweaks

- nocts_cata_mod_BN/Npc/c_classes.json
- nocts_cata_mod_DDA/Npc/c_classes.json
Simple fix, the random chance to spawn with Toe Talons would interact badly with potentially spawning boots.
> Fix error message caused by gladiators with Toe Talons

- nocts_cata_mod_DDA/Surv_help/c_armor.json
Simple copy-paste error during the updates to keep up with armor data
changes in DDA, easily fixed.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/347
> Fix survivor sabatons in DDA version

- nocts_cata_mod_BN/Monsters/c_monsters.json
- nocts_cata_mod_DDA/Monsters/c_monsters.json
- nocts_cata_mod_DDA/Monsters/c_ranged_monster.json
* Fixed augmented undead soldiers in the DDA version using the old workaround for monster ranged attacks not playing well with `FIRE_X` flags, now that `ammo_to_fire` is a thing. Since I dunno if it'll still work right it's easy to just update the workaround to use the newer method of specifying ammo per shot.
* Also have the augmented undead juggernauts the pathing flag to at least avoid fire, since the launcher version tends to have trouble with that.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/355
> Updates to augmented undead soldiers

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
Fixes stealth cloaks having a wrongly-pluralized plural name that still alludes to the days when you needed to switch them on and off.
> Smol typofix

- nocts_cata_mod_DDA/Mutations/c_bio_mutation_super_soldier.json
Easy fix, evidently they flipped blood loss vitamin_rate stuff to be backwards or whatever now.
> Update blood loss recovery in DDA version

- nocts_cata_mod_DDA/Mutations/c_bio_mutation_category.json
- nocts_cata_mod_DDA/Surv_help/c_comestibles.json
- nocts_cata_mod_DDA/Surv_help/c_effects.json
- nocts_cata_mod_DDA/Surv_help/c_vitamins.json
Per discussion in DMs with Noct, he said it's still fitting to have existing mutagenic content in Cata++ work like mutagen does now, so I can put off implementing any "better mutagenic behavior using EOC stuff" for after I test out using EOC for other stuff.
> Fix mutagen in DDA version

- nocts_cata_mod_BN/Vehicles/c_vehicles.json
- nocts_cata_mod_DDA/Vehicles/c_vehicles.json
Companion update to a BN PR, after confirming that reins and tackle actually work as vehicle controls for horse-drawn vehicles.
It does mean you can't cheese the gun cart's turret and remote-firing it by slapping a turret control unit on it, but if you can do that you can already swap the reins for vehicle controls as it is.
> Give survivor gun cart reins instead of controls

- nocts_cata_mod_DDA/Recipe/c_recipes.json
Easy recipe update, not needed for BN version since it still uses level-2 glare.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/374
> Belatedly update glare quality in DDA version

- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
- nocts_cata_mod_DDA/legacy.json
* Belatedly added some gun cleaning items to wasteland drifter like what the vanilla renactors start with, after confirming that yes the pistol does eventually foul.
* Added `NO_QUICKDRAW` flag to survivor's leg rig, because the "press f, opt to draw gun" thing doesn't work right if the gun in question isn't basically the last item added, when multi-holster items are involved.
* Obsoleted and migrated makeshift autoclaves from the DDA version. They might get a similar treatment in BN if I end up tinkering with the suggestion of making them craftable, but for now main focus is on fixing a bug.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/384
Existing makeshift autoclaves will complain about not being able to fit the diesel when first loaded in, but this error can be …
> Some assorted followup updates

- nocts_cata_mod_BN/Char_creation/c_classes_bw.json
- nocts_cata_mod_BN/Monsters/c_monster_drops.json
- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Monsters/c_monster_drops.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups_vanilla.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
* Set the Ominitech weapons to have all their default mods built-in. This fixes an exploit where you could remove their default mods, convert them to UPS, and have it regenerate fresh new default gunmods to remove.
* Set it so you can reverse conversion of the Omnitech weapons from UPS back to plutonium-powered, allow learning the recipe this way.
* Added the possibility for the UPS versions of Omnitech weapons to spawn. Generally about 50/50 in scientific settings, less often from augmented undead soldiers. Also allows the spare batteries on them to be either recharging or non-recharging. When the UPS version spawns, it also comes with a (reduced) chance to spawn a UPS, since sustained use might encourage supplementing the bionic UPS with an external one.
* Set it so non-recharging …
> Assorted Omnitech updates

- nocts_cata_mod_BN/Char_creation/c_classes_bw.json
- nocts_cata_mod_BN/Mutations/c_bio_mutation.json
- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Mutations/c_bio_mutation.json
Turns out that in both BN and DDA, the Expanded Digestion bionic covers all the effects of several metabolic mutations Alpha was given, so we can trim yet more mandatory trait points. As a bonus, gave the Metabolic Instability trait an effect that mitigates mutant toxins. Compared to Arcana's pending changes to Metabolic Resilience and Metabolic Adaptability, Metabolic Instability gains no extra toxin processing but does get even better reduction in toxin absorption, 25% instead of a max of 50%.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/389
> Remove redundant mutations from Bio-Weapon Alpha

- nocts_cata_mod_BN/Monsters/c_monster_harvest.json
- nocts_cata_mod_BN/Monsters/c_monster_override.json
- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_BN/Surv_help/c_effects.json
- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_BN/Surv_help/c_spells.json
- nocts_cata_mod_BN/Surv_help/c_tools.json
- nocts_cata_mod_DDA/Monsters/c_monster_harvest.json
- nocts_cata_mod_DDA/Monsters/c_monster_override.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_effects.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Surv_help/c_spells.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
* Added two new potential bits of mi-go biotech to salvage. One's implied to be a biomechanical spinneret for working with resin, the other would be what's left of the wings torn from a mi-go.
* Salvaging the spinneret yields an item that steadily regains charges over time, like the RTG inductive charger. It has two modes that can be swapped via transforming it, one to create a handful of resin chunks for crafting uses, the other mode serves as a repair item for items made of resin.
* Salvaging the wings yields an armor item that regenerates over time like the carapace armor does. When activated it lowers its encumbrance and grants a bonus to move cost and dodge, along with an effect that negates falling damage and a couple other related status effects. Active state also steadily drains …
> Implement more mi-go items to harvest

- nocts_cata_mod_DDA/Surv_help/c_techniques.json
Evidently needed for attacks to work in the DDA version.
Grab breaks and feints seem to not need it at least.
> Add attack vectors to DDA version

- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
Sets it so the fire modes of the ARC, AKRO, and KRX are a bit more consistent and less overkill. ARC gets shortest burst sizes, then AKRO, then KRX, also ensured the LMG has a semi-auto mode. Other side benefit of this is fire modes are now all sane fractions of expected battery capacity sizes.
Only real exception is the laser SMG can still accept ultra-light plutonium cells which gives only 25 shots worth of power, but it'd need burst side nerfed down even further for that to work sanely, when this degree of nerf still at least makes its max burst size a sane fraction of the light plutonium battery's capacity.
> Consistency updates for Omnitech fire rates

- nocts_cata_mod_BN/Monsters/c_monster_drops.json
- nocts_cata_mod_BN/Surv_help/c_bionics.json
- nocts_cata_mod_BN/Weapons/c_ammo.json
- nocts_cata_mod_DDA/Monsters/c_monster_drops.json
- nocts_cata_mod_DDA/Surv_help/c_bionics.json
- nocts_cata_mod_DDA/Weapons/c_ammo.json
* Did a similar fix to what I did with Arcana's Essence Surge Cell, splitting the Plasma Pulse Cell bionic into the main version for plasma canisters, and a sub-bionic included on installation specifically for loading hydrogen gas separately. This fixes the fact that loading the bionic with one of the ammo types breaks being able to use the other type at all until you've drained the tank dry, which is a big pain in the ass if the ammotype options have wildly different energy values.
* Set fuel spawns dropped by augmented abominations to have a minimum of one instead of zero. I'm at least somewhat confident this will fix the rare occurrence where an error message will sometimes print concerning hydrogen tanks, but hard to tell for sure since I've yet to find any way to reliably reproduce …
> Hydrogen-related updates

- nocts_cata_mod_BN/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Char_creation/c_classes_bw.json
- nocts_cata_mod_DDA/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_DDA/Npc/NC_SUPER_SOLDIERS.json
In the DDA version, set it so the bio-weapon/super soldier NPCs use the UPS versions of their relevant weapons. Turns out battery-fed weapons bug out and cause an AI loop for nested-container reasons in DDA, while UPS weapons work right in DDA (for now, given how unreliable NPC use of UPS weapons was even without nested containers being a buggy mess, I'd keep an eye on this and be prepared to start swapping in P90s and Rivtech guns if it breaks again).
Since I confirmed it's the other way around in BN (no reload loop, but NPCs treat UPS guns as melee weapons), left them unchanged in the BN version.
Also misc fix while I'm at it, set it so the failed bio-weapon profession doesn't start off wearing their makeshift earpro, in both versions.
Fixes …
> Update NPC lasers in DDA version, headgear fix

- nocts_cata_mod_DDA/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_DDA/Npc/NC_SUPER_SOLDIERS.json
Easy enough, just accidentally put in rechargeable versions it seems.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/422
> Fix wrong battery in DDA UPS spawns

- nocts_cata_mod_BN/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_BN/Npc/c_factions.json
- nocts_cata_mod_DDA/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_DDA/Npc/NC_SUPER_SOLDIERS.json
- nocts_cata_mod_DDA/Npc/c_factions.json
Some assorted updates to fix some stuff, mainly in DDA version but also a few matching BN version updates.
* Testing so far indicates that NPCs in DDA no longer break when trying to reload a gun that uses batteries (see issue: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/402), so I was able to remove the UPS spawns from super soldier NPCs, as they no longer had to use the UPS versions of the Omnitech guns. This fixed an issue where loading Cata++ with Aftershock would cause load errors because for some reason Aftershock overrides the UPS to have internal charges.
* Removed some unneeded faction relationship stuff for Cata++ factions so they won't sit there and take it if you attack them. Thisseems to be a DDA-specific bug but did the same for the BN version just in case.
* …
> Assorted NPC fixes

- nocts_cata_mod_BN/Surv_help/c_martialarts.json
A recent BN PR ported the Barbaran Montante martial art over from DDA, so now both the DDA and BN version inject makeshift greatsword into it.
> Barbaran Montante weapon injection for BN version

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Char_creation/c_start_locations.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
* Added mansion center as a valid place to start in the Surrounded scenario, combine with Medieval Mod Reborn for basically Hector start. :3
* Added a copy of BN's mansion center start location JSON to DDA version, since DDA favors starting in mansion basement instead.
* Allow starting as a failed bio-weapon in the mi-go captive scenario.
* Added crude lamp oil as an option to items in the DDA version that use assorted related fuels.
* Linted affected files.
> Scenario and DDA fuel updates

- nocts_cata_mod_BN/Surv_help/c_martialarts.json
- nocts_cata_mod_DDA/Surv_help/c_martialarts.json
These are a couple of updates geared towards giving Survivor Combatives a bit more defensive benefits that help give it parity with Post-Human Combaitves. In addition, it also adjusts one of the buffs of Post-Human Combatives to be a bit less counterintuitive to make proper use of.
* Added a static buff to Survivor Combatives at a high enough level, that adds a bonus bit of int-scaling speed boost.
* Added bash damage reduction, scaling off int, to Survivor Combative's on-hit buff.
* Shifted two layers of Post-Human Combatives' movecost bonuses from the onpause buff to a new onattack buff. This makes it easier to get the full use of the movecost bonuses, while still allowing the onpause buff to work as a setup buff.
* Belatedly added the hand-forged sword to Post Human Combatives' weapon …
> A few martial arts updates

- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
* Belatedly updated the wasteland drifter's starting inventory in the BN version, since bandoliers in BN can hold more ammo than in DDA.
* Also in both versions, fixed them starting with stabbing skill when their knife uses cutting skill.
> Wasteland drifter updates

- nocts_cata_mod_BN/Npc/c_npc.json
- nocts_cata_mod_DDA/Npc/c_npc.json
Simply just sets it so they can sell the stuff that spawns near them, easy fix.
> Fix survivor encampment NPCs

- nocts_cata_mod_BN/Mutations/c_bio_mutation.json
- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_BN/Terrain/makeshift_command_center.json
- nocts_cata_mod_BN/Vehicles/c_carts.json
- nocts_cata_mod_BN/Vehicles/c_vehicle_groups.json
- nocts_cata_mod_DDA/Mutations/c_bio_mutation.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Terrain/makeshift_command_center.json
- nocts_cata_mod_DDA/Vehicles/c_carts.json
- nocts_cata_mod_DDA/Vehicles/c_vehicle_groups.json
* Made description of makeshift power armor clarify what it does when active a bit better.
* Added Large size to Bio-Weapon Beta via a tweak to the Unyielding mutation unique to them.
* Adjusted mi-go carapace armor to fit the inner layer instead of armor, fitting the idea of it being a second skin and making it more usable with other armor types.
* Added a mutation-from-enchantment to carapace armor that adds some extra cooling if the user is overheating, and set active version to have zero warmth.
* Likewise reflavored the exo-wings a bit to justify them going on the waist slot instead of strapped, so that they don't compete with precious backpacks.
* Gave both carapace armor and ex-wings the `ONLY_ONE` flag.
* Allowed padding the scout suits and survivor cowboy hat with steel and/or …
> Bundle of assorted ideas

- nocts_cata_mod_DDA/Surv_help/c_bionics.json
- nocts_cata_mod_DDA/Weapons/c_melee.json
* Updated flags for the bionic sword weapon so it should work right in DDA again. Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/456
* Also belatedly implemented use of level-2 cutting quality for a few weapons that fit for it in DDA version, since that's a thing over there.
> Fix mono-sword in DDA version

- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/legacy.json
Converted stealth cloak in DDA version to call its relic data directly instead of using an enchantment. Code comment in the enchantment ID indicates we did that because effects from relic data didn't work at one point, but it works now when enchantments called directly likely that still don't work and I'm not sure if they've EVER worked.
Also marked some obsolete items in the legacy file as such in their item name to reduce confusion for people debugging.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/461
> Fix stealth cloak in DDA version again

- nocts_cata_mod_BN/Terrain/c_construction.json
- nocts_cata_mod_BN/Terrain/c_furniture.json
- nocts_cata_mod_BN/Vehicles/c_vehicle_parts.json
- nocts_cata_mod_DDA/Vehicles/c_vehicle_parts.json
Added grid-usable survivor's stations to BN version. Can't be merged yet as it depends on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2172 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2187 which will need to be merged first, and its construction category is also consistent with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2155.
Also belatedly updated the survivor's station item to use string weight, volume, and price; along with updating description to remind player what crafting stations are combined into it.
> Grid survivor stations for BN version

- nocts_cata_mod_BN/Weapons/c_ammo.json
Now that baseline paper cartridges in BN have some baseline armor penetration, shifted their stats a bit to not fully override.
DDA version untouched since no arpen on their version.
> Update Minie ball ammo in BN version

- nocts_cata_mod_DDA/Surv_help/c_bionics.json
- nocts_cata_mod_DDA/legacy.json
So turns out trickle chargers are a thing in DDA and that's been exactly what we needed to implement a fix for Atomic Battery in the DDA version without needing to resort to any weird hacky workarounds.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/471
> Fix for atomic battery in DDA version

- nocts_cata_mod_DDA/Surv_help/c_tools.json
Currently reading `survivor's cookbook` for one time takes 40 seconds. This is irrational and imbalanced, since this can level up crafting skill insanely quickly. I make it take 40 minutes to read once.
> Fix survivor's cookbook reads too fast

- nocts_cata_mod_BN/Surv_help/c_bionics.json
- nocts_cata_mod_BN/legacy.json
Setting this aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2291 is merged, updating the Atomic Battery CBM to not act as weird in BN version.
Also need to see if I can find any kinda hacky workarounds for the DDA version, but I'll do that as a separate PR.
> Updates to Atomic Battery CBM

- nocts_cata_mod_DDA/Surv_help/c_tools.json
Due to merge commit 4d5e209 to the main experimental branch flag fish_poor&fish_good was eliminated. Usage is nested to qualities of "fishing_rod".
> Fishing string obsolete flags

- nocts_cata_mod_BN/Terrain/Survivor_Encampments.json
- nocts_cata_mod_BN/Terrain/overmap_special.json
- nocts_cata_mod_BN/Terrain/overmap_terrain.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Terrain/Survivor_Encampments.json
- nocts_cata_mod_DDA/Terrain/overmap_special.json
- nocts_cata_mod_DDA/Terrain/overmap_terrain.json
1. Fixed proficiency stuff in DDA version, due to https://github.com/CleverRaven/Cataclysm-DDA/pull/64079 together with copy-pasting fail multipliers and the like no longer needed since proficiencies can define defaults for that.
2. Finished the split of survivor encampments and adding roof levels to them. Now each variation has a different unique overmap special, standardizing around 25% chance for uninhabited versions and 50% for ones with NPCs. This also accordingly fixes the issue where weird map extras could spawn on the NPC-inhabited version.
I also plan to at some point add arcanist variations to some of the encampments to the Arcana/Cata++ patchmod, to go with this.
> DDA recipe update, split up encampments more

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
Easy enough fix to something I forgot about, fixes a case of a zero-time reversible recipe, something no longer allowed in BN. Also updated DDA version for consistency just in case.
> Fix uncraft time

- nocts_cata_mod_BN/Terrain/c_furniture.json
- nocts_cata_mod_BN/Terrain/makeshift_command_center.json
1. Removed a spawn of items under rubble now that rubble in BN version gets shovel yield automatically.
2. Prevent dragging grid survivor station since dragging grid furniture can potentially cause problems it turns out.
> Updates for BN version

- nocts_cata_mod_BN/Terrain/Mapgen_Variants.json
Simply updates the variant of one necropolis tile with some standardization from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2670 in mind.
Unlike the Arcana equivalent this doesn't really introduce any changes that'll break or look weird if merged early, so I'll test this in a bit and see if it's okay to merge.
> Pending BN Update: Necropolis Update 1

- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
Simple tweak now that I've remembered that bionic sword is meant to be cutting rather than unarmed, plus the profession starts with melee skills and not the CQB bionic so that's needed to complete the set.
> Add cutting skill to bionic silencer

- nocts_cata_mod_BN/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_BN/Npc/NC_SUPER_SOLDIERS.json
- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_tools.json
- nocts_cata_mod_BN/legacy.json
- nocts_cata_mod_DDA/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_DDA/Npc/NC_SUPER_SOLDIERS.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
- nocts_cata_mod_DDA/legacy.json
* Added uncrafts to note and map items.
* Fixed survivor encampment map to point to the new versions of them.
* Obsoleted the map that only points to the single-NPC prepper location, since it didn't spawn anywhere and the location it points to if I recall spawns on roads now.
* Removed map from Evy's inventory since it's while it might explain how she found the location (aside from just Evy being Evy), it's just redundant to the player since they're already there.
* Removed map items from the super soldier and bio-weapon NPCs at the command center, being largely redundant by the time you reach that location plus a map to the unknown lab already spawns in the command center if you somehow beef it and softlock Router's mission.
> Assorted updates involving prepper/lab map items

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
Lil tweak to energy efficiency of makeshift power armor. Stated turns per charge is meant to fit a rate of power draw double that of regular power armor, relative to the fuel value of the least-efficient fuel usable.
Per that, lamp oil and motor have 26 kJ per unit, power armor draws a total of 2 kW, so makeshift power armor would have 4 kW power draw, making each unit of fuel last 6.5 turns (reasonable to round down to an even 6).
> Adjustment to makeshift power armor

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_tools.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
Updated the hammer multitool's tool qualities. Gains level 1 prying since claw hammers have that, the BN version gets level 1 bullet pulling since pliers have that (and it's probably more robust than the vanilla multi-tool which doesn't gain it).
Also added the `HACKSAW` use action to the makeshift wire saw, and updated the recipe to require superglue or bone glue due to the required abrasive.
> Hammer multitool and wire saw updates

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
Simple lil thing set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2908 is merged, adds the following professions to the new assassination scenario:
* Bio-Weapon Delta
* Super Scout
* Bionic Silencer
Not relevant for DDA since it seems their implementation was done purely via missions attached to the relevant professions.
> Pending BN updates: assassination scenario

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
Added a few alternatives to some items for the makeshift thermal lance recipe. Splitting it up into the main tool itself and refillable tanks, like the acetylene torch, would be the overall more complete way to fix this since the whole "uncraft it into surviving components" thing effectively transmutates clay canisters into canisters and leather hoses into rubber hoses, but doing so isn't really exploitable. Less hassle than trying to work around needing to use oxygen packs as tools in the recipe, if not for that I could just make the main recipe itself reversible and add `NO_RECOVER` to the components that will be lost on uncraft.
> Update to makeshift thermal lance recipe

- nocts_cata_mod_BN/Vehicles/c_carts.json
- nocts_cata_mod_BN/Vehicles/c_vehicles.json
- nocts_cata_mod_DDA/Surv_help/c_techniques.json
- nocts_cata_mod_DDA/Vehicles/c_carts.json
- nocts_cata_mod_DDA/Vehicles/c_vehicles.json
Discovered that DDA prefers `parts` array exclusively for vehicle definitions. So this meant now was as good a time as any to convert vehicle defs to use parts array in both versions since it's less annoying to read. Also fixes forgotten change to how frame variations are handled in DDA version and an update to martial arts.
> Update vehicle JSON, other fixes

- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Monsters/c_monsters.json
Sets it so that wasteland drifter starts with both a Colt Navy and Army, with a total of 1 stack of ammo for each, divided up as their storage items allow.
During testing I learned that DDA managed to screw it up such that the Colt Army can't fit in any vanilla holster as far as I could determine:
As such I shrugged, said "fuck it" and decided to upgrade them to a survivor's leg rig in both versions, despite them lacking the base skills needed to make it. Also makes it feel less messy in the BN version via fixing the the layering problems that came from juggling a holster, sheath, and canteen. Not a big buff aside from saving a tiny bit of leg encumbrance and making inventory juggling less hassle.
Also fixes grab attacks for monsters in the DDA version.
> Update for wasteland drifter, DDA fixes

- nocts_cata_mod_BN/Char_creation/c_classes_r.json
- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_DDA/Char_creation/c_classes_r.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
1. Added another post-apoc profession: wasteland techno-barbarian. Starts off with the bare minimum needed to craft the makeshift power armor they start with, along with having the means to make lamp oil to keep their armor fueled. Meant to be a way to dive in and mess with content, high strength and/or Strong Back comes in handy for this. Went ahead and kept it melee-focused, original idea was to add the full-auto shotgun too but that adds a fair bit of weight and even more skills when they already start with a lot.
2. Added wasteland techno-barbarian to scenarios that allow wasteland drifter and knight-errant.
3. Added bionic silencer, wasteland drifter, wasteland knight-errant, and wasteland techno-barbarian to prepper house scenario.
4. Set survivor knight-errant to use the survivor's …
> New profession and misc

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
1. Reworked range of the survivor's flintlock sniper to be a but less than the new range the long rifle has.
2. Updated the survivor's cowboy hat so it can hold paper shot, which got shifted to a separate ammotype to preclude rifles using them.
Simple updates in response to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3171/files
> Flintlock updates for BN version

- nocts_cata_mod_BN/Mutations/c_bio_mutation.json
Set aside as a draft for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2911 is merged, as now custom dialogue flags for mutations need their own definitions as `mutation_flags` entries.
> Pending BN Update: Mutation Flag JSON

- nocts_cata_mod_BN/Surv_help/c_books.json
- nocts_cata_mod_DDA/Surv_help/c_books.json
This sets aside an update for the BN version for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2910 is merged. Gives the flesh weapon recipe book the `BOOK_CANNIBAL` flag so that cannibal characters (along with psychopath and sapiovore characters) will be okay with it.
Also misc, fixed a typo in the item's description in both version.
> Pending BN update: fleshed out book morale effects

- nocts_cata_mod_DDA/Surv_help/c_techniques.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/68418 removed the powerful_knockback technique.
The field didn't do anything even before deprecation, so I'm following 68418 as an example by not replacing the field with anything.
> Remove  powerful_knockback from DDA technique

- nocts_cata_mod_BN/Surv_help/c_armor.json
Set aside for after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3691 is merged, implements the new `HEAVY_WEAPON_SUPPORT` flag in the BN version.
Added to active makeshift power armor, consistent with how active power armor currently has it. If the idea of making the flag stack with size mutations is reinstated, this would also become a mutant-friendly way to reap the benefits of being Huge and having a `HEAVY_WEAPON_SUPPORT` item.
Also added it to the makeshift ballistic pavise, making it currently the only passive source of the flag. Idea is the damn thing is big and hefty enough, combined with it being designed to leave both hands free for operating two-handed weapons, that it can be used as a potable mantlet to rest a firearm on.
> Pending BN Update: HEAVY_WEAPON_SUPPORT flag

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
Seems in BN and DDA the improvised gun itemgroups don't use nested gun spawns so the amount of updating needed was very minimal.
> Use nested gun spawns for sketchy cabin

- nocts_cata_mod_BN/Terrain/makeshift_command_center.json
- nocts_cata_mod_BN/Terrain/sketchy_cabin.json
- nocts_cata_mod_DDA/Terrain/makeshift_command_center.json
- nocts_cata_mod_DDA/Terrain/sketchy_cabin.json
Adjusted the layout and NPC placement of the sketchy cabin NPCs so that they won't immediately fight as soon as you enter the reality bubble. While it makes a neat setpiece for the scenario, when the player encounters the area normally it's pretty much guaranteed that they'll start enough ruckus to attract the others and without the PC Red Team will typically always beat the Blue Team NPCs.
The adjusted layout also includes a side connection to enter the secured area from the spectator's room that's locked up, and boarded-up doors preventing. This way if the player spawns in the spectator area they have a potential way to go either direction, but will have to get past Red Team to do so. This also means no more need to use the special buffed-up viewport terrain that was intended to get the …
> NPC zone updates

- nocts_cata_mod_DDA/Surv_help/c_books.json
CDDA added the 'manual' category to skillbooks in https://github.com/CleverRaven/Cataclysm-DDA/pull/53852#issue-1090194548 . Adding this category to skillbooks in cataclysm++ so there isn't a mismatch
> Add 'manual' category to skillbooks

- nocts_cata_mod_BN/Monsters/c_monster_harvest.json
- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Monsters/c_monster_harvest.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3719 is merged. Uses the new system of harvest itemgroups to make CBM generation less predictable, defining relevant itemgroups for dissecting failed bio-weapons, augmented undead soldiers, etc. Also now the BN version includes relevant non-biotech items for dissecting mi-gos.
Went ahead and allowed Apophis to stay at generating his CBMs at a 100% rate on the basis that he's a special boss critter so he can afford to reward CBMs more reliably than the norm.
Also belatedly applied a minor change influenced by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3538 to make superalloy skin more prominant for augmented abomination harvests.
> Pending BN update: bionic harvest variation

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3769 is merged, which adds a new bionic itemgroup for military stuff that Cata++ could logically add to.
> Pending BN update: new bionic itemgroup

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
Adds a couple of vanilla military professions to Experimental Soldier scenario, mainly bionic soldiers. Only in BN version because none of the vanilla professions in DDA really matched the theme, no bionics or experimental tech.
Set aside as WIP since one of the professions included is the power armor soldier to be added when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3771 is merged.
> Add some relevant vanilla professions to scenario

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3781 is merged. Adds the atomic battery, hazard shield, biopattern distortion, and cutting torch CBMs to the new `bionics_survivalist` item group.
> Pending BN Update: bionics_survivalist itemgroup

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_BN/Surv_help/c_tools.json
Set aside as a draft for if https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3792 is merged. Adds the `COMPACT` flag to the scout's tool, paracord watch, paracord bracelet, inductive CBM charger, salved exo-wings, survivor leg rig
> Pending BN feature: more use of COMPACT flag

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Weapons/c_magazines.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3836 is merged, turns out only thing really affected by this was the balance of the UPS crank rifle's magazine. Since it's implied to be 600 kJ's worth of storage (but holds less technically for game balance reasons since hand crank charging is slow as fuck), item accordingly tweaked to match new expected weight and volume while recipe no longer uses a 750-kJ option.
> Pending BN update: battery rebalancing

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_DDA/Char_creation/c_scenarios.json
Adds the super soldier professions to the aircraft carrier scenario in BN version, now that it's been ported from DDA, and add to DDA version too while I'm at it.
> Add professions to CVN Sailor scenario

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3956 is merged. Depends on it since the superalloy plate armor items that survivor superalloy plate armor uses as a component is obviously important to have in the JSON.
Adds superalloy versions of the following items:
* Survivor's armored scout suit
* Survivor plate armor (including components)
* Survivor great helm
* Survivor armored gauntlets
* Survivor armored boots
* Makeshift power armor
* Makeshift ballistic pavise
Follows the same general conventions as the related BN PRs set: 60% the base item's weight, double the price/post-apoc price (when defined), 5 lower encumbrance (set explicitly for the time being due to bugs with relative and proportional); meanwhile the recipes use 2 higher fabrication skill …
> Pending BN update: superalloy versions of craftable steel armor

- nocts_cata_mod_BN/Surv_help/c_armor.json
Lil update to BN version in the wake of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4004
Adds compatibility with the `resized_large` clothing mod to the following items:
1. Survivor's archer backpack
2. Light military armor
3. Military armor
4. Heavy military armor
5. Light military helm
6. Military helm
7. Heavy military helm
Survivor scout suits already had `OVERSIZE`+`VARSIZE` explicitly so no need for for it, carapace armor and makeshift power armor natively had `OVERSIZE`, meanwhile all the flavor items as well as survivor plate armor and survivor cowboy hats inherit from `VARSIZE` stuff and thus would automatically get access to the clothing mod already too.
> Add use of resized_large to BN version

- nocts_cata_mod_BN/Weapons/c_ranged.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4179 is merged, basically most uses of the gun slot mount gettin' replaced with just directly letting you bubba up a gun as desired.
> Pending BN Update: Mount Slot Obsoletion

- nocts_cata_mod_BN/Terrain/c_furniture.json
Simple lil self-PR set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4129 is merged, just applies the feature to grid survivor stations in BN version.
> Pending BN Update: Take Cover!

- nocts_cata_mod_DDA/Npc/c_factions.json
https://github.com/CleverRaven/Cataclysm-DDA/pull/71546 altered how faction food supply definitions work, among other things
I'm not entirely sure what justification was used for giving some factions vitamins but other factions no vitamins, but I believe its reasonable that if factions have an established food supply that they also have some relevant vitamins as well.
> Update DDA faction food supply

- nocts_cata_mod_BN/Recipe/c_recipes.json
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4264 phased out the makeshift arc welder in BN, in favor of just being able to craft regular welders like we already can with soldering irons, so this updates recipes accordingly.
> Welding recipe update

- nocts_cata_mod_BN/Vehicles/c_vehicle_parts.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4293 is merged. Simply adds use of the new material cost for repairing electronic vehicleparts to Cata++ parts, since the only repairable parts all tend to be that sorta thing.
> Pending BN Update: vehicle repairs use materials

- nocts_cata_mod_DDA/Mutations/c_bio_mutation.json
- nocts_cata_mod_DDA/Mutations/c_bio_mutation_super_soldier.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_bionics.json
- nocts_cata_mod_DDA/Vehicles/c_vehicles.json
More things moved to enchantments. Notably "thirst_modifier" was completely removed without replacement since it wasn't in use in the upstream repo, so that would require a PR there to put back in. Please take a look at the MENDING_MODIFIER values to see if that's working as intended to, some weirdness there since the only upstream examples were mending_modifier: 16 -> MENDING_MODIFIER: 15. Shotpaper was removed. Reapers and plows were made structural so the associated frames were removed from the tractor.
> Changes to match upstream updates

- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
Done due to https://github.com/CleverRaven/Cataclysm-DDA/pull/74417 obsoleting one of the pistols and magazines used in it, replaced with the Ruger pistol.
Side note, tempted to port that to BN someday...
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/627
> Update .22 aux pistol recipe and mag use

- nocts_cata_mod_BN/Recipe/c_uncraft.json
Now that BN has craftable CBMs in addition to being able to uncraft several of them, this adds uncrafts to some of the CBMs in the BN version of Cata++, based mainly on which CBMs in vanilla can be taken apart.
Adds uncrafts for the following:
1. Laser Gatling Arm CBM. Uncraft mostly based off the vanilla uncraft for finger laser, but swaps in more of the smaller lenses in place of standard ones and adds an alloy sheet for housing of the lasers.
2. Dual-Hand Flamethrower CBM. Took the basic components of the vanilla finger lighter, doubled them up, then added a few components from the Omnitech plasma pistol's recipe, along with the standard targeting module common to ranged attack CBMs.
3. Hazard Stabilizer System CBM. Mostly blended components from the uncrafts for Climate Control and …
> Allow disassembling certain CBMs in BN version

- nocts_cata_mod_DDA/Surv_help/c_techniques.json
In https://github.com/CleverRaven/Cataclysm-DDA/pull/73064 the format for attack_vector definitions changed to allow for extra specificity/unhardcoding/etc.  This PR converts the old attack vector definitions to the new ones based on the linked PR's example with the DDA techniques.
Note: The current attack_vector definitions do not throw a startup error but will fail when actually trying to use them.
Fixes #620
> [DDA] Convert martial arts technique attack_vectors to new format

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
Some basic consistency updates in light of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4868 adding a fairly similar concept with the survivor power armor.
1. Main one, renamed to makeshift hydraulic armor to better distinguish from survivor power armor.
2. Toned down EP to 3 to match survivor power armor.
3. Set it so the speed gain is lower than active survivor power armor, but gains more in strength boost.
> Some consistency updates to makeshift power armor

- nocts_cata_mod_BN/Recipe/c_recipes.json
A lil update now that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4954 has been merged, setting the newly-updated reference books as potential booklearns for several relevant recipes in the BN version of the mod.
> BN Update: Reference Books Actually Useful

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
- nocts_cata_mod_BN/Vehicles/c_vehicles.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Vehicles/c_vehicles.json
Small update since reloaded ammo was obsoleted in BN, adding in a random choice between standard and black powder 7.62 for the survivor gun cart spawns, while also updating the DDA version accordingly.
> Adjustment to survivor gun carts

- nocts_cata_mod_DDA/Monsters/c_monster_drops.json
- nocts_cata_mod_DDA/Npc/NC_BIO_WEAPONS.json
- nocts_cata_mod_DDA/Npc/NC_SUPER_SOLDIERS.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups.json
- nocts_cata_mod_DDA/Surv_help/c_item_groups_vanilla.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
- nocts_cata_mod_DDA/Terrain/Mapgen_Variants.json
- nocts_cata_mod_DDA/Terrain/Survivor_Encampments.json
- nocts_cata_mod_DDA/Weapons/c_magazines.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
Fixes DDA version due to https://github.com/CleverRaven/Cataclysm-DDA/pull/75865 having removed nice things from DDA yet again.
Not only do Omnitech batteries have to be standalone and no longer streamlined by copy-from, but now have to fully replace the standard atomic batteries for Omnitech stuff.
Did all this for heavy ones too even though those are still in DDA because zero ability to trust those will stay.
Fixes https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/645
> Fix DDA version of the mod due to batteries being broken

- nocts_cata_mod_BN/Recipe/c_recipes.json
- nocts_cata_mod_BN/Weapons/c_ammo.json
- nocts_cata_mod_DDA/Recipe/c_recipes.json
- nocts_cata_mod_DDA/Weapons/c_ammo.json
Makes minie ball recipe autolearn since unlike .36 and .44 ammo the baseline vanilla recipes for paper cartridges autolearn. Also makes it reversible.
In exchange however, toned down the range multiplier of minie ball down from 4x to 2x, since when combined with a rifled flintlock it had more range than the reality bubble.
> Updates to minie ball ammo

- nocts_cata_mod_BN/Vehicles/c_vehicle_parts.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5429 is merged. Turrets that previously had foldable status explicitly set now just set their `folded_volume` to match the item form's volume, and finally uses string volumes instead of legacy integers. Survivior flamethrower meanwhile doesn't get folding volume set since it's 5 liters, and that's the default volume it'll inherit from the turret abstract.
> Pending BN Update: foldable turrets

- nocts_cata_mod_BN/Surv_help/c_item_groups.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5635 is merged, swaps out the old injection of full-auto receiver cases into `drugdealer` (now being overhauled into a collection itemgroup) in favor of injecting it into `auto_sears` (which is called by drug dealer spawns and elsewhere).
> Pending BN Update: spawn receiver cases in `auto_sears` instead of `drugdealer`

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5644 is merged, adds the new post-apoc profession to the prepper household scenario since post-apoc professions in general are currently permitted in it.
> Pending BN Update: new post-apoc profession

- nocts_cata_mod_BN/Weapons/c_mods.json
- nocts_cata_mod_BN/Weapons/c_ranged.json
- nocts_cata_mod_DDA/Weapons/c_mods.json
- nocts_cata_mod_DDA/Weapons/c_ranged.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5769 is merged, updats reload rate of pneumatic LMG to be twice that of pnuematic assault rifle, and gave survivor flamethrower a fixed reload time now that reload rate won't be multiplied by number of rounds loaded.
> Pending BN Update: reload rate fixes

- nocts_cata_mod_BN/Surv_help/c_martialarts.json
- nocts_cata_mod_BN/Surv_help/c_techniques.json
- nocts_cata_mod_DDA/Surv_help/c_martialarts.json
- nocts_cata_mod_DDA/Surv_help/c_techniques.json
Per feedback, split some of the high-damage bonuses for Post-Human Combatives so that they only apply with weapons, since unarmed weapons can often get wacky DPS when combined with these effects. Unarmed-focused counterparts focus on stunning and displacing your target instead of knockback+knockdown, and the follow-up move likewise involves piledriving a stunned target instead of squishing a downed target.
Lastly, removed one-handed axes since it's now only used by hatchets and the like. One-handed hammers stay for now since warhammers use it, though I worry that warhammers, maces, and the like may still end up being the optimal weapons for this style.
> Some updates to Post-Human Combatives

- nocts_cata_mod_BN/Surv_help/c_bionics.json
- nocts_cata_mod_DDA/Surv_help/c_bionics.json
Updates BN version of plasma cutter to match the power usage of an arc welder when used to cut tools, consistent with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6206 having made 1 charge_per_use of the oxytorch worth the same 10:2 ratio seen in `welding_standard`.
Likewise tweaked DDA version a bit to match.
> Plasma cutter updates

- nocts_cata_mod_DDA/Monsters/c_monstergroups.json
- nocts_cata_mod_DDA/Surv_help/c_tools.json
- nocts_cata_mod_DDA/legacy.json
Hi,
This is my first time using git so please handle this with appropriate lack of respect for my competence.
Was installing the latest experimental and got a bunch of errors, I went into the files and changed the following and it stopped the errors:
The book fields "fun" and "skill" are now "read_fun" and "read_skill" as per https://github.com/CleverRaven/Cataclysm-DDA/pull/80490
The tool ammo field "ammo" is now "tool_ammo" as per https://github.com/CleverRaven/Cataclysm-DDA/pull/80490
"weight" and volume fields no longer accept int, added changed from eg 123 to "123g". I'm not 100% on what the bare numbers were supposed to represent in units, so please double check they make sense
"starts" field also no longer accepts int, I made similar changes assuming the numbers were hours.
> Update some field names and weight formats to work with DDA changes

- nocts_cata_mod_BN/Char_creation/c_scenarios.json
- nocts_cata_mod_BN/Monsters/c_monsters.json
See: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6363
As of the 2025-04-29 nightly, this change prevents the game from loading with nocts_cata_mod enabled
> Remove FILTHY tag from BN

- nocts_cata_mod_BN/Surv_help/c_armor.json
- nocts_cata_mod_DDA/Surv_help/c_armor.json
Set aside for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6731 is merged, gives the new flight ability to a trait granted by active exo-wings. Need to figure out if it works as a static mutation or if it can only ever be activated, though.
> Pending BN Update: "Yeah, They Fly Now."

- nocts_cata_mod_BN/Surv_help/c_tools.json
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6963 allows for melee weapons in BN to use whatever damage type they want, so implemented the ability to turn tazer blades on like shock tonfas and converted solar torches to no longer use `FLAMING` flag.
> BN feature: elemental melee damage
